Repository opencast/opencast-admin-interface, pull requests merged in 2024-03, with the labels that each got.

#261 Modernize redux: seriesDetailsSlice
  app/src/actions/seriesDetailsActions.ts
  app/src/components/events/partials/EventActionCell.tsx
  app/src/components/events/partials/ModalTabsAndPages/SeriesDetailsAccessTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/SeriesDetailsStatisticTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  app/src/components/events/partials/SeriesActionsCell.tsx
  app/src/components/events/partials/modals/SeriesDetails.tsx
  app/src/reducers/seriesDetailsReducers.ts
  app/src/selectors/seriesDetailsSelectors.ts
  app/src/slices/seriesDetailsSlice.ts
  app/src/slices/statisticsSlice.ts
  app/src/store.ts
  app/src/thunks/seriesDetailsThunks.ts
Labels: code-enhancement

#269 Modernize redux: eventDetailsSlice
  app/src/actions/eventDetailsActions.ts
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAccessPolicyTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachmentDetails.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachments.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogDetails.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogs.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMedia.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublicationDetails.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublications.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsPublicationTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsStatisticsTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowDetails.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrorDetails.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrors.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperationDetails.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperations.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  app/src/components/events/partials/modals/EventDetails.tsx
  app/src/reducers/eventDeatilsReducers.ts
  app/src/selectors/eventDetailsSelectors.ts
  app/src/slices/eventDetailsSlice.ts
  app/src/slices/workflowSlice.ts
  app/src/store.ts
  app/src/thunks/eventDetailsThunks.ts
  app/src/utils/dateUtils.ts
Labels: code-enhancement

#209 Typing /app/src/utils/utils.ts
  app/src/components/events/partials/modals/SeriesDetails.tsx
  app/src/slices/userInfoSlice.ts
  app/src/utils/utils.ts
Labels: typing

#291 Adds typing for table configs
  app/src/configs/tableConfigs/aclsTableConfig.ts
  app/src/configs/tableConfigs/eventsTableConfig.ts
  app/src/configs/tableConfigs/groupsTableConfig.ts
  app/src/configs/tableConfigs/jobsTableConfig.ts
  app/src/configs/tableConfigs/recordingsTableConfig.ts
  app/src/configs/tableConfigs/seriesTableConfig.ts
  app/src/configs/tableConfigs/serversTableConfig.ts
  app/src/configs/tableConfigs/servicesTableConfig.ts
  app/src/configs/tableConfigs/themesTableConfig.ts
  app/src/configs/tableConfigs/usersTableConfig.ts
  app/src/slices/aclSlice.ts
Labels: typing

#292 Type expected acl endpoint results
  app/src/selectors/aclSelectors.ts
  app/src/slices/aclSlice.ts
Labels: typing

#302 Fix typing issues from utils
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  app/src/utils/utils.ts
Labels: typing

#289 Fix typescript complaints about tabIndex
  app/src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/EditScheduledEventsGeneralPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewAssetUploadPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewProcessingPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewThemePage.tsx
  app/src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/StartTaskGeneralPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/StartTaskWorkflowPage.tsx
  app/src/components/shared/NewResourceModal.tsx
  app/src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  app/src/components/shared/wizard/RenderField.tsx
  app/src/components/shared/wizard/WizardNavigationButtons.tsx
  app/src/components/users/partials/wizard/AclAccessPage.tsx
  app/src/components/users/partials/wizard/AclMetadataPage.tsx
  app/src/components/users/partials/wizard/GroupMetadataPage.tsx
Labels: code-enhancement

#280 Update react-i18next dependency to 14.x.x
  app/package-lock.json
  app/package.json
  app/src/components/Header.tsx
  app/src/components/configuration/partials/ThemesActionsCell.tsx
  app/src/components/events/partials/EventActionCell.tsx
  app/src/components/events/partials/EventsDateCell.tsx
  app/src/components/events/partials/EventsLocationCell.tsx
  app/src/components/events/partials/EventsPresentersCell.tsx
  app/src/components/events/partials/EventsSeriesCell.tsx
  app/src/components/events/partials/EventsStatusCell.tsx
  app/src/components/events/partials/EventsTechnicalDateCell.tsx
  app/src/components/events/partials/SeriesActionsCell.tsx
  app/src/components/events/partials/SeriesTitleCell.tsx
  app/src/components/events/partials/modals/EventDetailsModal.tsx
  app/src/components/events/partials/modals/SeriesDetailsModal.tsx
  app/src/components/recordings/partials/RecordingsActionCell.tsx
  app/src/components/recordings/partials/RecordingsNameCell.tsx
  app/src/components/shared/MainNav.tsx
  app/src/components/shared/Stats.tsx
  app/src/components/shared/TableFilterProfiles.tsx
  app/src/components/shared/TableFilters.tsx
  app/src/components/shared/wizard/RenderMultiField.tsx
  app/src/components/shared/wizard/SelectContainer.tsx
  app/src/components/systems/partials/ServicesActionsCell.tsx
  app/src/components/users/partials/AclsActionsCell.tsx
  app/src/components/users/partials/GroupsActionsCell.tsx
  app/src/components/users/partials/UsersActionsCell.tsx
  app/src/components/users/partials/wizard/NewUserWizard.tsx
  app/src/components/users/partials/wizard/UserEffectiveRolesTab.tsx
  app/src/index.tsx
Labels: dependencies

#278 Remove bourbon-neat
  app/package-lock.json
  app/package.json
  app/src/styles/components/data-filter/_popout.scss
  app/src/styles/components/modals/_modal-components.scss
  app/src/styles/main.scss
Labels: dependencies

#295 Replace logout request with redirect
  app/src/components/Header.tsx
Labels: bug

#284 Reduce state persisted by redux-persist
  app/src/store.ts
Labels: bug, enhancement

#310 Reduce state persisted by redux-persist (reopen)
  app/src/components/statistics/Statistics.tsx
  app/src/store.ts
Labels: bug

#277 Update Material UI to v5
  app/package-lock.json
  app/package.json
  app/src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  app/src/components/events/partials/modals/EditMetadataEventsModal.tsx
  app/src/components/events/partials/wizards/NewEventWizard.tsx
  app/src/components/shared/TableFilters.tsx
  app/src/components/shared/TimeSeriesStatistics.tsx
  app/src/components/shared/wizard/RenderField.tsx
  app/src/components/shared/wizard/WizardStepper.tsx
  app/src/components/shared/wizard/WizardStepperEvent.tsx
  app/src/index.tsx
  app/src/utils/wizardUtils.ts
Labels: enhancement, dependencies
