Repository opencast/opencast-admin-interface, pull requests merged in 2024-09, with the labels that each got.

#887 Fix rendering of selection fields in metadata bulk editing
  src/slices/eventSlice.ts
  src/utils/resourceUtils.ts
Labels: type:bug

#313 Port Tobira integration
  src/components/events/Series.tsx
  src/components/events/partials/ModalTabsAndPages/NewTobiraPage.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsTobiraTab.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/events/partials/modals/SeriesDetails.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesSummary.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/components/shared/Notifications.tsx
  src/components/shared/wizard/WizardNavigationButtons.tsx
  src/configs/modalConfig.ts
  src/i18n/org/opencastproject/adminui/languages/lang-de_DE.json
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/selectors/seriesDetailsSelectors.ts
  src/selectors/seriesSeletctor.ts
  src/slices/notificationSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/styles/components/_breadcrumbs.scss
  src/styles/views/modals/_event-series.scss
  src/styles/views/modals/_new-event-series.scss
Labels: type:enhancement

#886 Properly type `createPolicy`
  src/utils/resourceUtils.ts
Labels: type:typing

#888 Fix checkmarks for multi-valued fields in bulk metadata editing
  src/components/events/partials/modals/EditMetadataEventsModal.tsx
Labels: type:bug

#848 Properly set theme default configuration
  src/components/events/partials/modals/SeriesDetails.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/components/shared/MainNav.tsx
Labels: type:code-enhancement

#884 Include admin interface version
  index.html
  vite.config.ts
Labels: type:enhancement

#913 Add ellipsis to filter box
  src/components/shared/TableFilters.tsx
  src/styles/main.scss
Labels: type:usability

#800 Fix required metadata not being required
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/utils/validate.ts
Labels: type:bug
