Repository opencast/opencast-admin-interface, pull requests merged in 2024-06, with the labels that each got.

#514 Update date-fns to 3.6.0
  package-lock.json
  package.json
  src/i18n/languages.ts
  src/index.tsx
Labels: type:dependencies

#515 Some vite nitpicks
  package-lock.json
  package.json
  vite.config.ts
Labels: type:code-enhancement

#490 Add check-label workflow
  .github/dependabot.yml
  .github/workflows/check-label.yml
Labels: type:infrastructure

#491 add release configuration
  .github/release.yml
Labels: type:infrastructure

#496 Set CI=true in all workflows
  .github/workflows/deploy-main.yml
  .github/workflows/deploy-test.yml
  .github/workflows/test.yml
Labels: type:tests

#521 Fix minor spelling mistakes in utils.ts
  src/utils/utils.ts
Labels: type:code-enhancement

#522 Properly align wizard stepper labels
  src/components/shared/wizard/WizardStepper.tsx
  src/components/shared/wizard/WizardStepperEvent.tsx
  src/utils/wizardUtils.ts
Labels: type:bug, type:visual-clarity

#512 Update @mui/material to 5.15.9
  package-lock.json
  package.json
  src/components/shared/wizard/CustomStepIcon.tsx
  src/utils/wizardUtils.ts
Labels: type:dependencies

#554 Fix dialog button sizes and margin
  src/styles/components/modals/_footer.scss
  src/styles/components/modals/_wizard.scss
Labels: type:visual-clarity

#537 Add size as variable to lang string
  src/components/events/partials/modals/EmbeddingCodeModal.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:visual-clarity

#511 Update @reduxjs/toolkit to 2.2.5
  package-lock.json
  package.json
  src/slices/healthSlice.ts
Labels: type:dependencies

#556 Show only one flavour separator in create event summary
  src/components/events/partials/wizards/NewEventSummary.tsx
Labels: type:visual-clarity

#513 Update dependency muixdatepickers
  package-lock.json
  package.json
  src/components/shared/TableFilters.tsx
Labels: type:dependencies

#494 Add .dockerignore
  .dockerignore
Labels: type:infrastructure

#568 Fix type error when opening statistics page
  src/components/statistics/Statistics.tsx
Labels: type:bug

#546 External links in new pages
  src/components/Header.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachmentDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMedia.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublicationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsPublicationTab.tsx
Labels: type:usability

#571 Fix notification when changing series theme
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
Labels: type:bug

#573 Fix render warning
  index.html
Labels: type:code-enhancement

#572 Fix several save-button misplacements in the event and series details
  src/components/events/partials/ModalTabsAndPages/DetailsExtendedMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
Labels: type:visual-clarity

#565 Fix button misplacmenet in the comment section and cleanup css
  src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  src/styles/components/modals/_modal-components.scss
Labels: type:visual-clarity

#560 Persist table pagination settings
  src/store.ts
Labels: type:bug

#579 Update Deployment Comment
  .github/workflows/deploy-test.yml
Labels: type:tests

#581 Simplify code for Notifications.tsx
  src/components/shared/Notifications.tsx
Labels: type:code-enhancement

#401 dont display ui when logged out
  src/App.tsx
  src/slices/userInfoSlice.ts
Labels: type:bug

#493 remove unused static languages.json
  public/languages.json
Labels: type:code-enhancement

#495 Type RenderField.tsx
  src/components/shared/wizard/RenderField.tsx
  src/components/shared/wizard/RenderMultiField.tsx
  src/slices/eventSlice.ts
Labels: type:typing

#497 Typing SelectContainer.tsx
  src/components/shared/wizard/SelectContainer.tsx
Labels: type:typing

#576 Aligning the rendering of the "Edit Table View" with other modal footers
  src/components/shared/EditTableViewModal.tsx
  src/styles/extensions/views/modals/_edit-table-view.scss
Labels: type:visual-clarity

#580 Remove race condition in table filters
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/recordings/Recordings.tsx
  src/components/systems/Jobs.tsx
  src/components/systems/Servers.tsx
  src/components/systems/Services.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
Labels: type:bug

#585 Admin interface creates invalid ACLs
  src/utils/resourceUtils.ts
Labels: type:bug

#586 Reset copy success message
  src/components/events/partials/modals/EmbeddingCodeModal.tsx
Labels: type:usability

#587 Submitter undefined
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowDetails.tsx
Labels: type:bug

#553 Add discernible text to prev/next pagination buttons.
  src/components/shared/Table.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:accessibility

#591 Add page size option '1000'
  src/components/shared/Table.tsx
  src/styles/components/_dropdowns.scss
Labels: type:enhancement

#592 Prevent concurrent main deployments
  .github/workflows/deploy-main.yml
Labels: type:github_actions

#563 Fix misplaced themes details menu navigation buttons
  src/styles/components/modals/_nav.scss
Labels: type:visual-clarity

#582 Update react and get rid of mui styles
  package-lock.json
  package.json
  src/components/shared/wizard/CustomStepIcon.tsx
  src/components/shared/wizard/WizardStepper.tsx
  src/components/shared/wizard/WizardStepperEvent.tsx
  src/index.tsx
  src/utils/wizardUtils.ts
Labels: type:dependencies

#594 Fix padding in edit table buttons
  src/styles/extensions/components/_drag-and-drop.scss
Labels: type:visual-clarity

#602 Only display date in series table created cell
  src/components/events/partials/SeriesDateTimeCell.tsx
Labels: type:visual-clarity

#621 Added option so unselect a theme in series view
  src/slices/seriesDetailsSlice.ts
Labels: type:bug

#589 Enhance color contrast ratio of stats.
  src/styles/components/_stats.scss
Labels: type:accessibility

#558 Add labels to checkboxes on Events tab.
  src/components/shared/Table.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:accessibility

#634 Fix license strings not being translated in metadata dropdown
  src/components/shared/DropDown.tsx
  src/components/shared/wizard/RenderField.tsx
  src/utils/dropDownUtils.ts
  src/utils/resourceUtils.ts
Labels: type:bug, bugbash

#619 Add esc hotkey to close modals
  src/components/events/partials/modals/DeleteEventsModal.tsx
  src/components/events/partials/modals/DeleteSeriesModal.tsx
  src/components/events/partials/modals/EditMetadataEventsModal.tsx
  src/components/events/partials/modals/EditScheduledEventsModal.tsx
  src/components/events/partials/modals/EmbeddingCodeModal.tsx
  src/components/events/partials/modals/EventDetailsModal.tsx
  src/components/events/partials/modals/SeriesDetailsModal.tsx
  src/components/events/partials/modals/StartTaskModal.tsx
  src/components/recordings/partials/modal/RecordingDetailsModal.tsx
  src/components/shared/ConfirmModal.tsx
  src/components/shared/EditTableViewModal.tsx
  src/components/shared/HotKeyCheatSheet.tsx
  src/components/shared/NewResourceModal.tsx
  src/components/shared/RegistrationModal.tsx
  src/components/shared/TableFilterProfiles.tsx
  src/components/users/partials/modal/AclDetailsModal.tsx
  src/components/users/partials/modal/GroupDetailsModal.tsx
  src/components/users/partials/modal/UserDetailsModal.tsx
  src/configs/hotkeysConfig.ts
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:usability

#635 Collapse roles in user table
  src/components/users/partials/UsersRolesCell.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:visual-clarity

#642 Trim workflow description
  src/components/events/partials/wizards/RenderWorkflowConfig.tsx
Labels: type:visual-clarity

#646 Remove dead code
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/recordings/partials/RecordingsActionCell.tsx
  src/components/statistics/Statistics.tsx
  src/components/users/partials/GroupsActionsCell.tsx
  src/components/users/partials/UsersActionsCell.tsx
Labels: type:code-enhancement

#648 Fix manifest.json and index.html
  index.html
  public/icons/icon-1024x1024.png
  public/icons/icon-144x144.png
  public/icons/icon-192x192.png
  public/icons/icon-256x256.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/manifest.json
Labels: type:visual-clarity

#606 Avoid rendering "Invalid date"
  src/components/events/partials/EventsDateCell.tsx
  src/components/events/partials/EventsTechnicalDateCell.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrorDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrors.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/components/shared/RenderDate.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/wizard/RenderField.tsx
  src/components/systems/partials/JobsSubmittedCell.tsx
  src/components/systems/partials/MeanRunTimeCell.tsx
Labels: type:bug, type:visual-clarity

#626 Fix handling of long strings in modal windows and table
  src/styles/main.scss
Labels: type:bug, bugbash

#666 Fix layout of file upload in add event dialog
  src/styles/main.scss
Labels: type:bug, type:visual-clarity

#627 Fix filter functionality and performance
  src/components/shared/TableFilterProfiles.tsx
  src/components/shared/TableFilters.tsx
Labels: type:bug, type:code-enhancement, type:visual-clarity, bugbash

#667 Fix file upload labels
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/styles/main.scss
Labels: type:bug, type:visual-clarity

#564 Move all HTML content into ARIA landmarks.
  src/components/About.tsx
  src/components/MainView.tsx
  src/components/NavBar.tsx
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/recordings/Recordings.tsx
  src/components/statistics/Statistics.tsx
  src/components/systems/Jobs.tsx
  src/components/systems/Servers.tsx
  src/components/systems/Services.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/styles/main.scss
Labels: type:accessibility

#659 Fix Set Filter Profile dialog behavior and styles
  src/components/shared/TableFilterProfiles.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/slices/tableFilterProfilesSlice.ts
  src/styles/components/data-filter/_filter-profiles.scss
Labels: type:usability, bugbash

#675 Fix Release Script
  .github/build-release.sh
  .github/workflows/create-release.yml
Labels: type:infrastructure

#677 Update Documentation
  README.md
Labels: type:documentation

#645 changing the hamburger menu icon color to have a better contrast ratio
  src/styles/components/_header.scss
Labels: type:accessibility

#647 change the roll up menu icon color to have a better contrast ratio
  src/styles/components/_menu.scss
Labels: type:accessibility

#649 Change the color of placeholder text input and textarea fields to a darker gray
  src/styles/components/_inputs.scss
Labels: type:accessibility, state:ICLA missing

#650 Change color of link and button text in action bar above tables to have a better contrast ratio
  src/styles/extensions/components/_tables.scss
Labels: type:accessibility, state:ICLA missing

#663 Change color of fa buttons in actions column to have a better contrast ratio
  src/styles/components/_tables.scss
Labels: type:accessibility

#665 use darkgray instead of gray to increase contrast ratio
  src/styles/components/modals/_modal-base.scss
Labels: type:accessibility

#593 Use @mui/material's Tooltip instead of `title` attributes.
  src/components/Header.tsx
  src/components/configuration/partials/ThemesActionsCell.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/EventsDateCell.tsx
  src/components/events/partials/EventsLocationCell.tsx
  src/components/events/partials/EventsPresentersCell.tsx
  src/components/events/partials/EventsSeriesCell.tsx
  src/components/events/partials/EventsStatusCell.tsx
  src/components/events/partials/EventsTechnicalDateCell.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/events/partials/SeriesTitleCell.tsx
  src/components/recordings/partials/RecordingsActionCell.tsx
  src/components/recordings/partials/RecordingsNameCell.tsx
  src/components/shared/MainNav.tsx
  src/components/shared/Stats.tsx
  src/components/shared/TableFilterProfiles.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/Tooltip.tsx
  src/components/systems/partials/ServicesActionsCell.tsx
  src/components/users/partials/AclsActionsCell.tsx
  src/components/users/partials/GroupsActionsCell.tsx
  src/components/users/partials/UsersActionsCell.tsx
  src/components/users/partials/wizard/NewUserWizard.tsx
  src/styles/components/_components-config.scss
  src/styles/components/_tooltips.scss
Labels: type:accessibility

#678 Enhance the color contrast in the events and series details modal.
  src/styles/base/_variables.scss
  src/styles/components/_header.scss
  src/styles/components/_stats.scss
Labels: type:accessibility

#680 Add text to icon buttons in the Edit Table dialog.
  src/components/shared/EditTableViewModal.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:accessibility

#668 add aria-live attribute
  src/components/shared/Notifications.tsx
Labels: type:accessibility

#575 Sort specific lists in dropdown menu alphabetically
  src/utils/dropDownUtils.ts
Labels: type:usability

#679 Add `aria-label` to the filter select element.
  src/components/shared/TableFilters.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:accessibility

#657 Fix unnecessary green ticks in Metadata wizard
  src/components/shared/wizard/RenderMultiField.tsx
Labels: type:bug, question, bugbash

#584 Show build information
  src/components/Footer.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/slices/userInfoSlice.ts
Labels: type:visual-clarity

#676 Move build instructions to Actions workflow
  .github/build-release.sh
  .github/workflows/create-release.yml
Labels: type:infrastructure

#681 Switch to node:20-alpine container base image
  Dockerfile
Labels: type:tests

#685 Enable source maps
  vite.config.ts
Labels: type:tests

#653 event source upload: remove filename from blue button when remove file is clicked
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
Labels: type:bug, bugbash

#673 Fix Date Display in Add Event
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/utils/dateUtils.ts
Labels: type:bug

#674 Update start date for uploads when opening the add events dialog
  src/components/events/partials/wizards/NewEventWizard.tsx
Labels: type:bug

#683 Align content of the main table left
  src/styles/components/_tables.scss
  src/styles/extensions/components/_tables.scss
Labels: type:visual-clarity

#684 Fix admin interface crashing when rendering filters
  src/components/shared/TableFilters.tsx
Labels: type:bug

#686 Scheduling information in event details for non-scheduled event
  src/components/events/partials/modals/EventDetails.tsx
  src/slices/eventDetailsSlice.ts
Labels: type:bug

#682 Correctly display “00” in event details scheduling
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
Labels: type:bug

#692 Add missing apple-touch-icon missed in #648
  public/logo-192x192.png
Labels: type:visual-clarity

#457 Correctly import zh-CN and zh-TW and remove language flags
  src/components/Header.tsx
  src/i18n/i18n.ts
  src/i18n/languages.ts
  src/img/lang/da_DK.svg
  src/img/lang/de_DE.svg
  src/img/lang/el_GR.svg
  src/img/lang/en_GB.svg
  src/img/lang/en_US.svg
  src/img/lang/es_ES.svg
  src/img/lang/fil_PH.svg
  src/img/lang/fr_FR.svg
  src/img/lang/gl_ES.svg
  src/img/lang/he_IL.svg
  src/img/lang/it_IT.svg
  src/img/lang/ja_JP.svg
  src/img/lang/nl_NL.svg
  src/img/lang/no_NO.svg
  src/img/lang/pl_PL.svg
  src/img/lang/readme.txt
  src/img/lang/sl_SI.svg
  src/img/lang/sv_SE.svg
  src/img/lang/tl_PH.svg
  src/img/lang/tr_TR.svg
  src/img/lang/zh_CN.svg
  src/img/lang/zh_TW.svg
  src/styles/components/_header.scss
  tsconfig.json
Labels: type:bug

#688 Center tooltips on main menu items
  src/components/shared/MainNav.tsx
Labels: type:visual-clarity

#660 Disable statistics tab by default
  src/components/shared/MainNav.tsx
Labels: type:bug

#687 Make themes optional
  src/components/events/partials/modals/SeriesDetails.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/components/shared/MainNav.tsx
Labels: type:visual-clarity

#690 Using correct config key to hide imprint and privacy policy links
  src/components/Footer.tsx
Labels: type:bug

#321 Respect config option for adding series ACL to new event
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
Labels: type:bug

#703 Fix pagination in capture agent table
  src/thunks/tableThunks.ts
Labels: type:bug

#664 increase contrast ratio in wizard modal
  src/styles/components/_steps.scss
Labels: type:accessibility

#700 Remove unused `eslint` config
  package.json
Labels: type:code-enhancement

#704 Make selected table filter smaller
  src/styles/main.scss
Labels: type:visual-clarity

#702 Refetch event ACL after saving
  src/slices/eventDetailsSlice.ts
Labels: type:bug

#707 `npm audit fix`
  package-lock.json
Labels: type:dependencies

#709 Get rid of Vite build warnings
  package-lock.json
  package.json
  vite.config.ts
Labels: type:code-enhancement

#720 Disable ACL save button
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
Labels: type:usability

#730 Don't show unsaved changes warning after saving
  src/components/events/partials/ModalTabsAndPages/EventDetailsAccessPolicyTab.tsx
Labels: type:bug

#740 Hide tooltip on hover
  src/components/shared/MainNav.tsx
  src/components/shared/Tooltip.tsx
Labels: type:visual-clarity

#739 Add tabs in event details assets
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachmentDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachments.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogs.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMedia.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublicationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublications.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsTab.tsx
  src/components/events/partials/modals/EventDetails.tsx
Labels: type:usability

#714 "Restore" ESLint support
  eslint.config.js
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/recordings/partials/RecordingsActionCell.tsx
  src/components/shared/Notifications.tsx
  src/components/statistics/Statistics.tsx
  src/components/users/partials/GroupsActionsCell.tsx
  src/components/users/partials/UsersActionsCell.tsx
Labels: type:code-enhancement

#705 Remove poorly formatted dead code
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
Labels: type:code-enhancement

#710 Table focus is not shown #617
  src/styles/base/_layout.scss
  src/styles/components/_dropdowns.scss
  src/styles/components/_inputs.scss
  src/styles/components/modals/_modal-components.scss
  src/styles/main.scss
  src/styles/mixins/_button.scss
  src/styles/views/_core.scss
  src/utils/componentStyles.ts
Labels: type:accessibility

#715 Fix type error for missing organization property
  src/components/Footer.tsx
  src/components/events/partials/modals/SeriesDetails.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/components/shared/MainNav.tsx
Labels: type:bug

#718 fix a11y issues in header nav
  src/components/Header.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-de_DE.json
  src/i18n/org/opencastproject/adminui/languages/lang-en_GB.json
  src/styles/components/_header.scss
Labels: type:accessibility

#724 Table filters cannot be reached with the keyboard #616
  src/components/shared/TableFilters.tsx
Labels: type:accessibility

#727 Hamburger menu cannot be reached with the keyboard #615
  src/components/shared/MainNav.tsx
  src/styles/components/_header.scss
Labels: type:accessibility

#737 Hide type and flavor of add asset items
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
Labels: type:visual-clarity, type:usability

#736 Einbettungscode Dialog a11y issues #625
  src/components/events/partials/modals/EmbeddingCodeModal.tsx
Labels: type:accessibility

#671 Use button tag for stat filter items
  src/components/shared/Stats.tsx
  src/styles/components/_stats.scss
Labels: type:accessibility

#743 Fix checkstyle issues and disable sourcemaps
  src/components/Header.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachmentDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachments.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogs.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMedia.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublicationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublications.tsx
  src/components/events/partials/modals/EventDetails.tsx
Labels: type:code-enhancement, priority:high
