Repository opencast/opencast-admin-interface, pull requests merged in 2024-05, with the labels that each got.

#328 Remove `wait` option from `react-i18next` initialization
  app/src/i18n/i18n.ts
Labels: dependencies, typing, code-enhancement

#329 Remove `Login` component and related bits
  app/src/components/Login.tsx
  app/src/i18n/org/opencastproject/adminui/languages/lang-da_DK.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-de_DE.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-el_GR.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-en_GB.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-es_ES.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-fr_FR.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-gl_ES.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-he_IL.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-it_IT.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-nl_NL.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-pl_PL.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-sl_SI.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-sv_SE.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-tr_TR.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-zh_CN.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-zh_TW.json
  app/src/setupProxy.js
  app/src/styles/base/_variables.scss
  app/src/styles/components/_inputs.scss
  app/src/styles/views/_login.scss
  app/src/styles/views/_views-config.scss
Labels: code-enhancement

#337 Simplify dependencies for the dev servers
  package-lock.json
  package.json
Labels: code-enhancement

#338 Fix the `server` `npm`-script
  package.json
Labels: code-enhancement

#276 Replace react-smooth-dnd with react-beautiful-dnd
  app/package-lock.json
  app/package.json
  app/src/components/shared/EditTableViewModal.tsx
Labels: bug, enhancement, dependencies

#293 Fix default routing
  app/src/App.tsx
Labels: bug

#303 Modernize redux: tableFilterProfilesSlice
  app/src/actions/tableFilterProfilesActions.ts
  app/src/components/shared/TableFilterProfiles.tsx
  app/src/reducers/tableFilterProfilesReducer.ts
  app/src/selectors/tableFilterProfilesSelectors.ts
  app/src/slices/tableFilterProfilesSlice.ts
  app/src/store.ts
Labels: code-enhancement

#320 Modernize Redux: AclThunks
  app/src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  app/src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  app/src/components/shared/wizard/WizardStepper.tsx
  app/src/components/shared/wizard/WizardStepperEvent.tsx
  app/src/components/users/partials/AclsActionsCell.tsx
  app/src/components/users/partials/modal/AclDetails.tsx
  app/src/components/users/partials/wizard/AclAccessPage.tsx
  app/src/components/users/partials/wizard/GroupRolesPage.tsx
  app/src/components/users/partials/wizard/NewAclWizard.tsx
  app/src/components/users/partials/wizard/UserRolesTab.tsx
  app/src/slices/aclSlice.ts
  app/src/thunks/aclThunks.ts
  app/src/utils/resourceUtils.ts
  app/src/utils/utils.ts
Labels: code-enhancement

#331 Select correct workflows for Start Task
  app/src/components/events/partials/ModalTabsAndPages/StartTaskWorkflowPage.tsx
Labels: bug

#341 Add license file and license information for package.json
  LICENSE
  package.json
Labels: code-enhancement

#342 Add ICLA Check
  .github/workflows/check-icla.yml
Labels: code-enhancement

#358 Document and link translation rules
  README.md
Labels: documentation

#340 Remove unused dependencies
  app/config-overrides.js
  app/package-lock.json
  app/package.json
  package-lock.json
  package.json
  proxyServer.js
Labels: dependencies

#345 Simplify the proxies
  app/src/setupProxy.js
  package-lock.json
  package.json
  proxyServer.js
  staticServer.js
  test/app/GET/capture-agents/agents.json
  test/app/GET/conflictCheckMultiple.json
  test/app/GET/conflictCheckSingle.json
  test/app/GET/conflictResponse.json
  test/app/GET/groups/groups.json
  test/app/GET/groups/it_team.json
  test/app/GET/i18n/languages.json
  test/app/GET/i18n/languages_de.json
  test/app/GET/newEventMultipleDSTFixture.json
  test/app/GET/newEventMultipleFixture.json
  test/app/GET/newEventSingleFixture.json
  test/app/GET/newEventUploadFixture.json
  test/app/GET/roles/roles.json
  test/app/GET/workflow/definitions.json
Labels: code-enhancement

#323 Fix unique key issue in new event summary page
  app/src/components/events/partials/wizards/summaryTables/MetadataExtendedSummaryTable.tsx
Labels: bug

#392 Harmonize date rendering between read-only and read/write fields
  app/src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  app/src/components/shared/RenderDate.tsx
  app/src/components/shared/wizard/RenderField.tsx
Labels: bug, code-enhancement

#387 Typing WizardStepperEvent
  app/src/components/shared/wizard/WizardStepperEvent.tsx
Labels: typing

#381 added i18n for subtitles, added subtitles to test file
  app/src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  test/app/GET/admin-ng/resources/eventUploadAssetOptions.json
Labels: bug

#396 Enable deleting user references from the admin UI
  app/src/components/users/partials/UsersActionsCell.tsx
Labels: enhancement, admin-ui-feature-tracking

#404 add typing and fix build
  app/src/components/shared/Table.tsx
Labels: bug

#325 Add typing to NewEventWizard.tsx
  app/src/components/configuration/partials/wizard/BumperPage.tsx
  app/src/components/configuration/partials/wizard/TitleSlidePage.tsx
  app/src/components/configuration/partials/wizard/WatermarkPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewAssetUploadPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewMetadataExtendedPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewMetadataPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewProcessingPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewThemePage.tsx
  app/src/components/events/partials/ModalTabsAndPages/StartTaskWorkflowPage.tsx
  app/src/components/events/partials/wizards/NewEventSummary.tsx
  app/src/components/events/partials/wizards/NewEventWizard.tsx
  app/src/components/events/partials/wizards/NewSeriesSummary.tsx
  app/src/components/events/partials/wizards/NewSeriesWizard.tsx
  app/src/components/events/partials/wizards/RenderWorkflowConfig.tsx
  app/src/components/shared/wizard/FileUpload.tsx
  app/src/configs/modalConfig.ts
  app/src/configs/sourceConfig.ts
  app/src/slices/eventDetailsSlice.ts
  app/src/slices/eventSlice.ts
  app/src/slices/seriesSlice.ts
  app/src/thunks/assetsThunks.ts
  app/src/utils/resourceUtils.ts
Labels: typing

#398 Pull the static file server into the CRA proxy as well
  .github/dependabot.yml
  .github/workflows/test.yml
  README.md
  app/src/setupProxy.js
  package-lock.json
  package.json
  staticServer.js
Labels: dependencies, code-enhancement

#275 Replace Hotkey library
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/shared/HotKeyCheatSheet.tsx
  src/components/shared/MainNav.tsx
  src/components/shared/TableFilters.tsx
  src/configs/hotkeysConfig.ts
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/index.tsx
Labels: enhancement, dependencies

#425 Remove `ts-migrate`
  package-lock.json
  package.json
Labels: dependencies

#427 fix linting errors in create-release GHA workflow
  .github/workflows/create-release.yml
Labels: code-enhancement

#416 Automatically Deploy Demo Page
  .github/demo-page.html
  .github/workflows/deploy.yml
Labels: code-enhancement

#459 Fix mock data file path after project restructuring
  .github/workflows/deploy.yml
Labels: code-enhancement

#220 Show conflicting scheduling events for new events
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/slices/eventSlice.ts
Labels: bug

#288 Fix tabbing in event details metadata
  src/components/shared/wizard/RenderField.tsx
  src/components/shared/wizard/RenderMultiField.tsx
Labels: bug, enhancement

#304 Modernize redux: tableFiltersSlice
  src/actions/tableFilterActions.ts
  src/components/Header.tsx
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/events/partials/EventsDateCell.tsx
  src/components/events/partials/EventsLocationCell.tsx
  src/components/events/partials/EventsPresentersCell.tsx
  src/components/events/partials/EventsSeriesCell.tsx
  src/components/events/partials/EventsStatusCell.tsx
  src/components/events/partials/EventsTechnicalDateCell.tsx
  src/components/events/partials/SeriesTitleCell.tsx
  src/components/recordings/Recordings.tsx
  src/components/recordings/partials/RecordingsNameCell.tsx
  src/components/shared/MainNav.tsx
  src/components/shared/Stats.tsx
  src/components/shared/TableFilterProfiles.tsx
  src/components/shared/TableFilters.tsx
  src/components/systems/Jobs.tsx
  src/components/systems/Servers.tsx
  src/components/systems/Services.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
  src/reducers/tableFilterReducers.ts
  src/selectors/tableFilterSelectors.ts
  src/slices/tableFilterProfilesSlice.ts
  src/slices/tableFilterSlice.ts
  src/store.ts
  src/thunks/tableFilterThunks.ts
  src/utils/resourceUtils.ts
Labels: code-enhancement

#406 fix i18n.options.fallbackLng
  src/components/About.tsx
  src/i18n/i18n.ts
  src/i18n/languages.ts
  src/utils/utils.ts
  test/GET/ui/config/admin-ui/imprint.en-US.html
  test/GET/ui/config/admin-ui/privacy.en-US.html
Labels: bug

#426 Fix i18n key for EVENTS.EVENTS.DETAILS.COMMENTS.REASONS.CANCELLED
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  test/GET/admin-ng/resources/components.json
Labels: bug

#468 Fix a command in the `README`
  README.md
Labels: bug, documentation

#407 Better naming for Crowdin workflows
  .github/workflows/crowdin-download-translations.yml
  .github/workflows/crowdin-upload-keys.yml
Labels: code-enhancement

#389 always add current user to acl
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
Labels: type:bug

#470 Automatically publish conatiner image
  .github/workflows/deploy-container-image.yaml
  Dockerfile
Labels: type:infrastructure

#430 Fix build warnings
  package-lock.json
  package.json
  src/components/configuration/partials/wizard/NewThemeWizard.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachmentDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublicationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsPublicationTab.tsx
  src/components/events/partials/modals/StartTaskModal.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/components/shared/TableFilterProfiles.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/TimeSeriesStatistics.tsx
  src/components/shared/wizard/RenderField.tsx
  src/components/shared/wizard/SelectContainer.tsx
  src/components/users/partials/wizard/NewUserWizard.tsx
  src/styles/base/fontawesome/_core.scss
  src/styles/base/fontawesome/_fixed-width.scss
  src/styles/base/fontawesome/_larger.scss
  src/styles/base/fontawesome/_list.scss
  src/styles/base/fontawesome/_mixins.scss
  src/styles/base/fontawesome/_variables.scss
  src/styles/components/_statistics-graph.scss
  src/styles/components/_stats.scss
  src/styles/components/_steps.scss
  src/styles/components/modals/_modal-base.scss
  src/styles/components/modals/_nav.scss
  src/styles/components/video/_video-editor.scss
  src/styles/mixins/_mixins-config.scss
  src/utils/bulkActionUtils.ts
Labels: type:code-enhancement

#460 Remove superflous SCSS for old video editor
  src/styles/components/_components-config.scss
  src/styles/components/video/_video-config.scss
  src/styles/components/video/_video-controls.scss
  src/styles/components/video/_video-editor.scss
  src/styles/components/video/_video-event-area.scss
  src/styles/components/video/_video-function-buttons.scss
  src/styles/components/video/_video-header.scss
  src/styles/components/video/_video-help-button.scss
  src/styles/components/video/_video-player.scss
  src/styles/components/video/_video-toolbar.scss
  src/styles/components/video/_video-view-controller.scss
  src/styles/components/video/popover/_animation.scss
  src/styles/components/video/popover/_base.scss
  src/styles/components/video/popover/_point.scss
  src/styles/components/video/popover/_popover-config.scss
  src/styles/components/video/popover/_table.scss
  src/styles/main.scss
Labels: type:code-enhancement

#349 Fail on warnings when building releases
  .github/build-release.sh
Labels: type:infrastructure

#461 Replace deprecated i18next-xhr-backend with i18next-http-backend
  package-lock.json
  package.json
  src/i18n/i18n.ts
Labels: type:dependencies
