Repository opencast/opencast-admin-interface, pull requests merged in 2024-08, with the labels that each got.

#846 Open player directly
  src/components/events/partials/PublishedCell.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:usability

#837 Simplify minimum of 0
  src/components/shared/wizard/WizardStepperEvent.tsx
Labels: type:code-enhancement

#836 Improve highlighting of active step
  src/styles/components/_steps.scss
Labels: type:visual-clarity

#874 Fix undefined values in adopter registration
  src/components/shared/RegistrationModal.tsx
Labels: type:bug

#824 Add more typing to resourceUtils
  src/components/events/partials/ModalTabsAndPages/DetailsExtendedMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/events/partials/modals/EditMetadataEventsModal.tsx
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/utils/resourceUtils.ts
Labels: type:typing

#833 Refactor various types in slices
  src/components/configuration/partials/wizard/ThemeDetails.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/users/partials/modal/AclDetails.tsx
  src/slices/aclDetailsSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/tableSlice.ts
  src/slices/themeDetailsSlice.ts
  src/slices/themeSlice.ts
  src/slices/userDetailsSlice.ts
  src/utils/resourceUtils.ts
Labels: type:typing

#697 Group events in bulk edit scheduled events tab
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
Labels: type:bug

#879 Fix the URL for the "about" configuration in the admin UI
  src/components/About.tsx
Labels: type:bug

#880 Fix some CI linting errors
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
Labels: type:code-enhancement

#859 Add system type dropdown in adopter registration
  src/components/shared/RegistrationModal.tsx
  src/configs/adopterRegistrationConfig.ts
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/utils/adopterRegistrationUtils.ts
Labels: type:enhancement
