Repository opencast/opencast-admin-interface, pull requests merged in 2024-04, with the labels that each got.

#285 Fix multivalue field not submitting
  app/src/components/shared/wizard/RenderMultiField.tsx
Labels: bug

#307 Fix workflow operations not refreshing
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperations.tsx
  app/src/components/events/partials/modals/EventDetails.tsx
Labels: bug

#312 Type usePageFunctions in wizardHooks.ts
  app/src/components/configuration/partials/wizard/BumperPage.tsx
  app/src/components/configuration/partials/wizard/GeneralPage.tsx
  app/src/components/configuration/partials/wizard/NewThemeWizard.tsx
  app/src/components/configuration/partials/wizard/ThemeSummaryPage.tsx
  app/src/components/configuration/partials/wizard/TitleSlidePage.tsx
  app/src/components/configuration/partials/wizard/WatermarkPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/EditScheduledEventsGeneralPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/EditScheduledEventsSummaryPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/StartTaskGeneralPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/StartTaskSummaryPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/StartTaskWorkflowPage.tsx
  app/src/components/events/partials/modals/EditScheduledEventsModal.tsx
  app/src/components/events/partials/modals/StartTaskModal.tsx
  app/src/components/shared/wizard/RenderField.tsx
  app/src/components/shared/wizard/RenderMultiField.tsx
  app/src/components/shared/wizard/WizardNavigationButtons.tsx
  app/src/components/shared/wizard/WizardStepper.tsx
  app/src/components/users/partials/modal/AclDetails.tsx
  app/src/components/users/partials/wizard/AclAccessPage.tsx
  app/src/components/users/partials/wizard/AclMetadataPage.tsx
  app/src/components/users/partials/wizard/GroupMetadataPage.tsx
  app/src/components/users/partials/wizard/GroupRolesPage.tsx
  app/src/components/users/partials/wizard/GroupUsersPage.tsx
  app/src/components/users/partials/wizard/NewAclSummaryPage.tsx
  app/src/components/users/partials/wizard/NewAclWizard.tsx
  app/src/components/users/partials/wizard/NewGroupSummaryPage.tsx
  app/src/components/users/partials/wizard/NewGroupWizard.tsx
  app/src/configs/modalConfig.ts
  app/src/hooks/wizardHooks.ts
  app/src/slices/eventSlice.ts
Labels: typing

#308 Remove various ts expect errors
  app/src/components/Header.tsx
  app/src/components/configuration/partials/ThemesActionsCell.tsx
  app/src/components/configuration/partials/wizard/NewThemeWizard.tsx
  app/src/components/configuration/partials/wizard/ThemeDetails.tsx
  app/src/components/configuration/partials/wizard/UsagePage.tsx
  app/src/components/events/Events.tsx
  app/src/components/events/Series.tsx
  app/src/slices/healthSlice.ts
  app/src/slices/themeDetailsSlice.ts
  app/src/slices/themeSlice.ts
Labels: typing

#314 Type dropdown
  app/src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewProcessingPage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  app/src/components/events/partials/ModalTabsAndPages/NewThemePage.tsx
  app/src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  app/src/components/events/partials/ModalTabsAndPages/StartTaskWorkflowPage.tsx
  app/src/components/shared/DropDown.tsx
  app/src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  app/src/components/users/partials/wizard/AclAccessPage.tsx
  app/src/utils/componentStyles.ts
  app/src/utils/dropDownUtils.ts
Labels: typing

#324 More util typing
  app/src/components/users/partials/wizard/NewUserWizard.tsx
  app/src/configs/modalConfig.ts
  app/src/slices/aclSlice.ts
  app/src/slices/eventSlice.ts
  app/src/slices/groupSlice.ts
  app/src/slices/jobSlice.ts
  app/src/slices/recordingSlice.ts
  app/src/slices/seriesSlice.ts
  app/src/slices/serverSlice.ts
  app/src/slices/serviceSlice.ts
  app/src/slices/themeSlice.ts
  app/src/slices/userDetailsSlice.ts
  app/src/slices/userSlice.ts
  app/src/utils/eventDetailsUtils.ts
  app/src/utils/resourceUtils.ts
  app/src/utils/workflowPanelUtils.ts
Labels: typing

#330 Remove an unused import
  app/src/components/Header.tsx
Labels: code-enhancement

#283 Add notes column back in
  app/src/components/events/partials/EventsNotesCell.tsx
  app/src/configs/tableConfigs/eventsTableConfig.ts
  app/src/configs/tableConfigs/eventsTableMap.ts
  app/src/i18n/org/opencastproject/adminui/languages/lang-de_DE.json
  app/src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  app/src/slices/eventDetailsSlice.ts
  app/src/slices/eventSlice.ts
  app/src/styles/components/_tables.scss
  app/src/thunks/tableThunks.ts
  test/app/GET/admin-ng/resources/components.json
Labels: enhancement

#281 Avoid crashing by not throwing error
  proxyServer.js
Labels: bug
