Repository opencast/opencast-admin-interface, pull requests merged in 2024-11, with the labels that each got.

#961 Fix "Start Task"
  src/components/events/partials/modals/StartTaskModal.tsx
Labels: type:bug

#958 URL-encode `filter` parameter for `/admin-ng`-endpoints
  src/utils/resourceUtils.ts
Labels: type:enhancement

#855 Fix undefined access error in empty access policies
  src/slices/eventDetailsSlice.ts
Labels: type:bug

#957 Fix border around date selector
  src/styles/main.scss
Labels: type:bug

#921 Open event details on the center of the page
  src/styles/main.scss
Labels: type:usability

#910 Fix translation for table name in EditTableModal
  src/components/shared/EditTableViewModal.tsx
Labels: type:bug

#912 Persist filters
  src/store.ts
Labels: type:bug

#978 Fix wf config values not showing for scheduled events
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/slices/eventDetailsSlice.ts
Labels: type:bug

#945 Fix test containers
  .github/workflows/deploy-container-image.yaml
  vite.config.ts
Labels: type:tests
