Repository opencast/opencast-admin-interface, pull requests merged in 2024-01, with the labels that each got.

#217 Fix publication link not clickable
  app/src/components/events/partials/PublishedCell.tsx
Labels: bug

#265 Update proxy-server run instructions
  README.md
Labels: documentation

#205 Fix exception when opening timepicker
  app/package-lock.json
  app/package.json
Labels: bug, dependencies

#239 Don't call Object.entries on undefined
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowDetails.tsx
Labels: bug

#241 Don't render "invalid date" in table cells
  app/src/components/events/partials/EventsEndCell.tsx
  app/src/components/events/partials/EventsStartCell.tsx
  app/src/components/events/partials/SeriesDateTimeCell.tsx
  app/src/components/recordings/partials/RecordingsUpdateCell.tsx
  app/src/components/systems/partials/JobsStartedCell.tsx
  app/src/components/systems/partials/MeanQueueTimeCell.tsx
  app/src/utils/dateUtils.ts
Labels: bug

#219 Refresh workflow operations in event details
  app/src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperations.tsx
Labels: bug

#271 Add quickstart guide and update development instructions
  README.md
Labels: documentation

#246 Remove useAppDispatch from tableThunks.ts
  app/src/thunks/tableThunks.ts
Labels: bug
