Repository opencast/opencast-admin-interface, pull requests merged in 2024-07, with the labels that each got.

#711 Typing event details
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsExtendedMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAccessPolicyTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachmentDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachments.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogs.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMedia.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublicationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublications.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsPublicationTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsStatisticsTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrorDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrors.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperations.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsAccessTab.tsx
  src/components/events/partials/modals/EventDetails.tsx
  src/components/events/partials/modals/EventDetailsModal.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/slices/eventDetailsSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/utils/resourceUtils.ts
Labels: type:typing

#728 Default typing for createAsyncThunk
  src/createAsyncThunkWithTypes.ts
  src/slices/aclDetailsSlice.ts
  src/slices/aclSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/groupDetailsSlice.ts
  src/slices/groupSlice.ts
  src/slices/healthSlice.ts
  src/slices/jobSlice.ts
  src/slices/notificationSlice.ts
  src/slices/recordingDetailsSlice.ts
  src/slices/recordingSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/serverSlice.ts
  src/slices/serviceSlice.ts
  src/slices/statisticsSlice.ts
  src/slices/tableFilterSlice.ts
  src/slices/themeDetailsSlice.ts
  src/slices/themeSlice.ts
  src/slices/userDetailsSlice.ts
  src/slices/userInfoSlice.ts
  src/slices/userSlice.ts
  src/slices/workflowSlice.ts
  src/thunks/assetsThunks.ts
Labels: type:typing, type:code-enhancement

#719 Allow admins to save ACLs with no write roles
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/slices/aclSlice.ts
Labels: type:enhancement

#746 Prevent sort icon from breaking table headers
  src/styles/main.scss
Labels: type:bug

#747 Add missing translation key
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:bug

#754 Deselect all rows after start task
  src/components/events/partials/modals/StartTaskModal.tsx
Labels: type:usability

#757 "Unsaved changes" popup showing up but changes are saved
  src/components/events/partials/ModalTabsAndPages/EventDetailsAccessPolicyTab.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsAccessTab.tsx
Labels: type:bug

#758 Use "presentation" instead of "slides" for upload
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:usability

#780 Prevent overflow by using flexbox in header nav bar
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
  src/styles/components/_header.scss
  src/styles/components/_stats.scss
Labels: type:visual-clarity

#782 Add typing to AclUtils.ts
  src/utils/aclUtils.ts
Labels: type:typing

#748 Remove some dead code
  src/components/shared/DropDown.tsx
  src/slices/eventDetailsSlice.ts
Labels: type:code-enhancement

#788 Add typing to BarChart
  src/components/shared/BarChart.tsx
Labels: type:typing

#787 Hide file remove button if no record file selected
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
Labels: type:visual-clarity, type:usability

#751 Main menu tooltip position
  src/components/shared/MainNav.tsx
Labels: type:visual-clarity

#777 Add typing to dateUtils.ts
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/shared/TimeSeriesStatistics.tsx
  src/utils/dateUtils.ts
Labels: type:typing

#778 Add typing to componentStyles.ts
  src/components/shared/DropDown.tsx
  src/utils/componentStyles.ts
Labels: type:typing

#779 Add typing to bulkActionUtils.ts
  src/utils/bulkActionUtils.ts
Labels: type:typing

#781 Add typing to RegistrationModal
  src/components/shared/RegistrationModal.tsx
  src/configs/adopterRegistrationConfig.ts
  src/utils/adopterRegistrationUtils.ts
Labels: type:typing

#783 Add typing to user details
  src/components/users/partials/modal/UserDetails.tsx
  src/components/users/partials/modal/UserDetailsModal.tsx
  src/components/users/partials/wizard/EditUserGeneralTab.tsx
  src/components/users/partials/wizard/NewUserGeneralTab.tsx
  src/components/users/partials/wizard/NewUserWizard.tsx
  src/components/users/partials/wizard/UserEffectiveRolesTab.tsx
  src/components/users/partials/wizard/UserRolesTab.tsx
  src/configs/modalConfig.ts
  src/slices/userDetailsSlice.ts
  src/slices/userSlice.ts
  src/utils/resourceUtils.ts
Labels: type:typing

#759 Add typing to wizard stepper
  src/components/shared/wizard/WizardStepper.tsx
  src/utils/wizardUtils.ts
Labels: type:typing

#755 Remove Tooltip from Stats Filter
  src/components/shared/Stats.tsx
Labels: type:visual-clarity

#785 Add typing to acl details
  src/components/users/partials/modal/AclDetails.tsx
  src/components/users/partials/modal/AclDetailsModal.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/components/users/partials/wizard/NewAclWizard.tsx
  src/configs/modalConfig.ts
  src/slices/aclSlice.ts
Labels: type:typing

#786 Add typing to ModalNavigation
  src/components/configuration/partials/wizard/ThemeDetails.tsx
  src/components/shared/modals/ModalNavigation.tsx
Labels: type:typing

#793 Replace title attribute in footer elements with tooltips
  src/components/Footer.tsx
Labels: type:visual-clarity

#795 Add typing to ConfirmModal
  src/components/shared/ConfirmModal.tsx
Labels: type:typing

#796 Add typing to NewResourceModal
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/shared/NewResourceModal.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
Labels: type:typing

#797 Add typing to RecordingDetailsModal
  src/components/recordings/partials/modal/RecordingDetailsModal.tsx
Labels: type:typing

#798 Add typing to validate.ts
  src/utils/validate.ts
Labels: type:typing

#784 Add typing to group details
  src/components/users/partials/modal/GroupDetails.tsx
  src/components/users/partials/modal/GroupDetailsModal.tsx
  src/components/users/partials/wizard/GroupUsersPage.tsx
  src/components/users/partials/wizard/NewGroupSummaryPage.tsx
  src/configs/modalConfig.ts
  src/slices/groupDetailsSlice.ts
  src/slices/groupSlice.ts
  src/utils/resourceUtils.ts
Labels: type:typing

#799 Fix empty presenters filter field in events
  src/components/shared/TableFilters.tsx
  src/slices/tableFilterSlice.ts
Labels: type:bug

#815 Port password strength indicator
  src/components/users/partials/wizard/NewUserGeneralTab.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/styles/components/_progress-bar.scss
Labels: type:enhancement

#818 Fix style of saved filter sets
  src/components/shared/TableFilterProfiles.tsx
  src/styles/components/data-filter/_filter-profiles.scss
Labels: type:bug, type:visual-clarity

#819 Set lower maximum z-index than tooltip index
  src/components/Header.tsx
  src/components/shared/Tooltip.tsx
  src/styles/base/_variables.scss
Labels: type:bug

#820 Fix tooltip title of saved filter
  src/components/shared/TableFilterProfiles.tsx
Labels: type:bug

#821 Show cursor pointer on header bar icons
  src/styles/components/_header.scss
Labels: type:bug

#822 Sort filters alphabetically
  src/components/shared/TableFilters.tsx
Labels: type:usability

#823 Add check mark to selected language
  src/components/Header.tsx
  src/styles/components/_header.scss
Labels: type:visual-clarity

#813 Fix unique key prop
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsTab.tsx
Labels: type:bug

#750 Asset-Upload fixed
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
Labels: type:bug

#801 Fix processing status translation key
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:bug

#729 Custom roles in ACL policy
  src/components/shared/DropDown.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:enhancement

#733 Add keyboard keys to remove focus on input fields
  src/components/configuration/partials/wizard/BumperPage.tsx
  src/components/configuration/partials/wizard/GeneralPage.tsx
  src/components/configuration/partials/wizard/TitleSlidePage.tsx
  src/components/configuration/partials/wizard/WatermarkPage.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsExtendedMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewMetadataExtendedPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewMetadataPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/events/partials/modals/EditMetadataEventsModal.tsx
  src/components/events/partials/wizards/RenderWorkflowConfig.tsx
  src/components/shared/Field.tsx
  src/components/shared/RegistrationModal.tsx
  src/components/shared/TimeSeriesStatistics.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/components/users/partials/wizard/AclMetadataPage.tsx
  src/components/users/partials/wizard/EditUserGeneralTab.tsx
  src/components/users/partials/wizard/GroupMetadataPage.tsx
  src/components/users/partials/wizard/NewUserGeneralTab.tsx
Labels: type:accessibility, type:usability

#841 Remove div container around select component
  src/components/shared/DropDown.tsx
Labels: type:bug

#831 Fix height of filters
  src/components/shared/TableFilters.tsx
  src/styles/main.scss
Labels: type:visual-clarity

#814 Fix video preview displaying wrong video
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
Labels: type:bug

#817 Show workflow operations when clicking on status in events table
  src/components/events/Events.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/EventsStatusCell.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachmentDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachments.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogs.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMedia.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublicationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublications.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrorDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrors.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperations.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/components/events/partials/modals/EventDetails.tsx
  src/components/events/partials/modals/EventDetailsModal.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/selectors/eventDetailsSelectors.ts
  src/slices/eventDetailsSlice.ts
  src/utils/eventDetailsUtils.ts
Labels: type:enhancement

#749 Add a very restricted form of `no-tabs` to the ESLint config
  eslint.config.js
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/components/shared/DropDown.tsx
  src/configs/modalConfig.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/notificationSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/workflowSlice.ts
  src/utils/dateUtils.ts
Labels: type:code-enhancement

#828 Fix missing key in metadata translations
  src/components/events/partials/ModalTabsAndPages/DetailsExtendedMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsSummaryPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewMetadataExtendedPage.tsx
  src/components/events/partials/wizards/summaryTables/MetadataExtendedSummaryTable.tsx
  src/components/events/partials/wizards/summaryTables/MetadataSummaryTable.tsx
  src/components/shared/wizard/RenderField.tsx
  src/utils/resourceUtils.ts
Labels: type:bug

#835 Fix recursion in effect when fetching series acls
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
Labels: type:bug

#842 Media type specific player
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
Labels: type:bug

#844 Simplify Opencast version display
  src/components/Footer.tsx
Labels: type:visual-clarity

#845 Drop translation of old editor
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:code-enhancement

#847 Typing of publication cell
  src/components/events/partials/PublishedCell.tsx
Labels: type:typing

#850 auto select workflow when there is only one
  src/components/events/partials/ModalTabsAndPages/NewProcessingPage.tsx
  src/components/events/partials/ModalTabsAndPages/StartTaskWorkflowPage.tsx
Labels: type:usability

#753 Improve embed codes
  src/components/events/partials/modals/EmbeddingCodeModal.tsx
Labels: type:bug

#816 Fix up registration modal
  src/components/shared/RegistrationModal.tsx
  src/configs/adopterRegistrationConfig.ts
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/styles/extensions/views/modals/_registration.scss
  src/utils/adopterRegistrationUtils.ts
Labels: type:enhancement

#843 Remove reset of error number
  src/components/Header.tsx
  src/slices/healthSlice.ts
Labels: type:bug

#857 Fix missing `agreedToPolicy` parameter when add adopter
  src/utils/adopterRegistrationUtils.ts
Labels: type:bug

#854 Show correct event details modal with table actions
  src/components/events/partials/EventActionCell.tsx
Labels: type:bug
