Repository opencast/opencast-admin-interface, pull requests merged in 2025-03, with the labels that each got.

#1116 Fix unique key error in NavBar
  src/components/NavBar.tsx
Labels: type:bug

#1133 Remove test deployment if PR is closed
  .github/workflows/remove-test.yml
Labels: type:github_actions

#1070 Remove feeds
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsFeedsTab.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/events/partials/modals/SeriesDetails.tsx
  src/selectors/seriesDetailsSelectors.ts
  src/slices/seriesDetailsSlice.ts
Labels: type:code-enhancement

#1075 Add typing to dropdown options
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewProcessingPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewThemePage.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  src/components/events/partials/ModalTabsAndPages/StartTaskWorkflowPage.tsx
  src/components/events/partials/wizards/scheduling/SchedulingLocation.tsx
  src/components/events/partials/wizards/scheduling/SchedulingTime.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/shared/wizard/RenderField.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/slices/eventSlice.ts
  src/utils/componentStyles.ts
  src/utils/dropDownUtils.ts
Labels: type:code-enhancement

#1086 Fix rendering of mean times
  src/components/systems/partials/MeanQueueTimeCell.tsx
  src/components/systems/partials/MeanRunTimeCell.tsx
Labels: type:bug

#1103 Enforce event ordering
  src/slices/eventSlice.ts
Labels: type:bug

#1112 Fix notes column loading slowly sometimes
  src/slices/eventSlice.ts
Labels: type:bug

#1115 Fix table action delete modal not opening
  src/components/events/Events.tsx
  src/components/events/Series.tsx
Labels: type:bug

#1117 Fix "Events" not bold on page load.
  src/components/NavBar.tsx
Labels: type:bug

#1119 Fix entering single date in date range picker
  src/components/shared/TableFilters.tsx
Labels: type:bug

#1120 Allow stats to set textfilter
  src/components/shared/Stats.tsx
Labels: type:bug, type:enhancement

#1122 Fix hiding tobira tab in series create modal
  src/components/events/partials/wizards/NewSeriesWizard.tsx
Labels: type:bug

#1138 It's “label” not “lable”
  .github/workflows/check-label.yml
Labels: type:infrastructure

#1137 Properly clean up pull requests
  .github/workflows/remove-test.yml
Labels: type:bug

#1139 Restore table checkboxes on load
  src/slices/tableSlice.ts
Labels: type:bug

#1145 Fix create modal strings
  src/components/shared/NewResourceModal.tsx
Labels: type:bug

#1146 Fix themes not being fetched
  src/components/shared/Table.tsx
  src/slices/tableSlice.ts
Labels: type:bug

#1140 Fix cancel button in column selection modal
  src/components/shared/EditTableViewModal.tsx
Labels: type:bug

#1147 Add missing env variable
  .github/workflows/remove-test.yml
Labels: type:github_actions

#1150 Fix typescript conflict for initial state of table field "resource"
  src/components/shared/Table.tsx
  src/selectors/tableSelectors.ts
  src/slices/tableSlice.ts
  src/thunks/tableThunks.ts
Labels: type:bug, type:typing

#1121 Reduce api requests
  src/components/About.tsx
  src/components/Header.tsx
  src/components/NavBar.tsx
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/events/partials/EventsNavigation.tsx
  src/components/events/partials/PublishedCell.tsx
  src/components/events/partials/SeriesTitleCell.tsx
  src/components/recordings/Recordings.tsx
  src/components/recordings/partials/RecordingsNameCell.tsx
  src/components/shared/MainNav.tsx
  src/components/shared/Stats.tsx
  src/components/shared/TableFilters.tsx
  src/components/statistics/Statistics.tsx
  src/components/systems/Jobs.tsx
  src/components/systems/Servers.tsx
  src/components/systems/Services.tsx
  src/components/systems/partials/SystemsNavigation.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
  src/components/users/partials/UsersNavigation.tsx
  src/selectors/tableSelectors.ts
  src/slices/eventSlice.ts
  src/slices/tableFilterSlice.ts
  src/slices/tableSlice.ts
  src/utils/resourceUtils.ts
Labels: type:enhancement

#1063 Reduce duplicate code - button like anchor
  src/components/Header.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsTobiraTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetAttachments.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetCatalogs.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMedia.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetPublications.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsTabHierarchyNavigation.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrors.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperations.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewAssetUploadPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/events/partials/ModalTabsAndPages/NewTobiraPage.tsx
  src/components/events/partials/PublishedCell.tsx
  src/components/events/partials/modals/EmbeddingCodeModal.tsx
  src/components/events/partials/modals/EventDetails.tsx
  src/components/events/partials/modals/SeriesDetails.tsx
  src/components/shared/ButtonLikeAnchor.tsx
  src/components/shared/EditTableViewModal.tsx
  src/components/shared/MainNav.tsx
  src/components/shared/Notifications.tsx
  src/components/shared/Table.tsx
  src/components/shared/TableFilterProfiles.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/modals/DetailsModal.tsx
  src/components/shared/modals/Modal.tsx
  src/components/shared/modals/ModalNavigation.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/shared/wizard/RenderMultiField.tsx
  src/components/shared/wizard/SelectContainer.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/components/users/partials/wizard/NewUserWizard.tsx
  src/components/users/partials/wizard/UserEffectiveRolesTab.tsx
Labels: type:code-enhancement

#698 Allow tracks in event asset upload
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAssetUploadPage.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/selectors/eventDetailsSelectors.ts
  src/selectors/eventSelectors.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/thunks/assetsThunks.ts
  src/utils/utils.ts
Labels: type:bug

#1162 Limit concurrency for deploy and remove test page
  .github/workflows/deploy-test.yml
  .github/workflows/remove-test.yml
Labels: type:enhancement

#1114 Reduce duplicate code for table action dropdown
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/shared/TableActionDropdown.tsx
Labels: type:code-enhancement

#1163 Improve phrasing of warning when deleting files
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:visual-clarity

#1160 Fix nested buttons in dropdown warning
  src/components/shared/Table.tsx
Labels: type:bug

#1159 Fix layouting errors in a various modals
  src/styles/mixins/_mixins-bourbon.scss
Labels: type:bug
