Repository opencast/opencast-admin-interface, pull requests merged in 2025-05, with the labels that each got.

#1130 Rewrite metadata fields for accessibility
  package-lock.json
  package.json
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/wizard/RenderField.tsx
  src/styles/main.scss
  src/utils/componentStyles.ts
Labels: type:enhancement

#1142 Fix event summary page crashing for dates
  src/components/events/partials/wizards/summaryTables/MetadataSummaryTable.tsx
Labels: type:bug

#1143 Reset workflow info on error
  src/slices/eventDetailsSlice.ts
Labels: type:bug

#1144 Remove rollup-preserve-directives
  package-lock.json
  package.json
  vite.config.ts
Labels: type:infrastructure

#1153 Fix being unable to step back in event modal
  src/components/events/partials/ModalTabsAndPages/NewAssetUploadPage.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
Labels: type:bug

#1181 Some minor refactorings
  src/components/events/partials/modals/EventDetails.tsx
  src/components/events/partials/modals/EventDetailsModal.tsx
  src/components/shared/modals/Modal.tsx
Labels: type:code-enhancement, priority:low

#1186 Improve word wrapping in tables
  src/components/events/partials/ModalTabsAndPages/StartTaskGeneralPage.tsx
  src/styles/components/modals/_modal-components.scss
  src/styles/main.scss
Labels: type:bug, priority:medium

#1158 Fix end time date display for scheduling
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/events/partials/wizards/scheduling/SchedulingEndDateDisplay.tsx
  src/components/events/partials/wizards/scheduling/SchedulingTime.tsx
Labels: type:visual-clarity, priority:low

#1161 Unify notifications
  src/components/events/partials/ModalTabsAndPages/EventDetailsStatisticsTab.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsStatisticTab.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/events/partials/modals/DeleteEventsModal.tsx
  src/components/events/partials/modals/DeleteSeriesModal.tsx
  src/components/shared/ActionCellDelete.tsx
  src/components/shared/ConfirmModal.tsx
  src/components/shared/Notifications.tsx
  src/components/statistics/Statistics.tsx
  src/components/users/partials/wizard/EditUserGeneralTab.tsx
  src/components/users/partials/wizard/UserRolesTab.tsx
  src/styles/components/_alerts.scss
  src/styles/components/_components-config.scss
  src/styles/components/modals/_modal-alerts.scss
  src/styles/components/modals/_modals-config.scss
Labels: type:visual-clarity, priority:medium

#1177 Remove "completed" column from servers table
  src/configs/tableConfigs/serversTableConfig.ts
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:bug, priority:low

#1178 Show service online status
  src/configs/tableConfigs/serversTableConfig.ts
  src/configs/tableConfigs/servicesTableConfig.ts
  src/configs/tableConfigs/servicesTableMap.ts
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/slices/serviceSlice.ts
Labels: type:enhancement, priority:medium

#1184 Tooltip text: delete organization
  src/components/users/partials/AclsActionsCell.tsx
  src/components/users/partials/GroupsActionsCell.tsx
  src/components/users/partials/UsersActionsCell.tsx
Labels: type:bug, priority:low

#1187 1180: Created values missing from themes table #1180
  src/components/configuration/partials/ThemesDateTimeCell.tsx
  src/configs/tableConfigs/themesTableConfig.ts
  src/configs/tableConfigs/themesTableMap.ts
  src/slices/themeSlice.ts
Labels: type:bug, priority:medium

#1199 Scheduling single event or multiple events times filed display wrong digits
  src/utils/dropDownUtils.ts
  src/utils/utils.ts
Labels: type:bug, priority:low

#1249 update npm and yarn/react hotkeys hook 5.0.1
  package-lock.json
  package.json
  src/components/shared/HotKeyCheatSheet.tsx
Labels: type:dependencies

#1245 Remove console.info statements from postNewGroup and deleteGroup thunks
  src/components/users/partials/wizard/NewGroupWizard.tsx
  src/slices/groupSlice.ts
Labels: type:code-enhancement

#1261 Close the language change dropdown without reloading the whole page
  src/components/Header.tsx
Labels: type:enhancement

#1252 Fix the disappearing filter when the bell icon is clicked
  src/slices/tableFilterSlice.ts
Labels: type:bug

#1165 Remove wrong component description
  src/components/shared/DropDown.tsx
Labels: type:documentation, priority:nice-to-have

#1169 Make wizard stepping more robust
  src/components/configuration/partials/wizard/NewThemeWizard.tsx
  src/components/configuration/partials/wizard/ThemeDetails.tsx
  src/components/events/partials/modals/EditScheduledEventsModal.tsx
  src/components/events/partials/modals/StartTaskModal.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/components/shared/wizard/WizardStepper.tsx
  src/components/users/partials/modal/AclDetails.tsx
  src/components/users/partials/wizard/NewAclWizard.tsx
  src/components/users/partials/wizard/NewGroupWizard.tsx
  src/utils/validate.ts
  src/utils/wizardUtils.ts
Labels: type:bug, type:code-enhancement, priority:low

#1234 No sorting for ROLES header in users page
  src/configs/tableConfigs/usersTableConfig.ts
  src/slices/userSlice.ts
Labels: type:enhancement

#1256 Updating groups now preserves previously selected roles
  src/components/users/partials/modal/GroupDetails.tsx
  src/slices/aclSlice.ts
Labels: type:bug, priority:critical

#1285 Modernize the `Dockerfile`
  Dockerfile
Labels: type:infrastructure

#1257 Make sure selected users are not listed in the users lists
  src/components/shared/wizard/SelectContainer.tsx
Labels: type:bug

#1282 Fix checkbox name for contact me field in RegistrationModal
  src/components/shared/RegistrationModal.tsx
Labels: type:bug

#1185 Replace MUI-datepicker with react-datepicker in the statistics component
  package-lock.json
  package.json
  src/components/shared/TimeSeriesStatistics.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/index.tsx
  src/styles/components/_components-config.scss
  src/styles/components/_date-picker.scss
  src/styles/components/_datepicker-custom.scss
  src/styles/components/_statistics-graph.scss
Labels: type:code-enhancement, type:visual-clarity, priority:low

#1278 Override events ACLs by separate button in Series Details Update
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsAccessTab.tsx
  src/components/shared/SaveEditFooter.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/slices/eventDetailsSlice.ts
  src/slices/seriesDetailsSlice.ts
Labels: type:bug, priority:high

#1268 Adding two missing translation keys
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:bug, type:translation

#1277 make cancel buttons work for users/groups/access
  src/components/users/partials/modal/AclDetails.tsx
  src/components/users/partials/modal/GroupDetails.tsx
  src/components/users/partials/modal/UserDetails.tsx
Labels: type:bug

#1281 Fix multiple upload notifications overlapping when uploading multiple videos
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/slices/eventSlice.ts
Labels: type:bug, priority:high

#1286 Deselect table rows when sorting
  src/components/shared/Table.tsx
Labels: type:bug

#1274 Broadcasting logout event in order to redirect other tabs to login page
  src/App.tsx
  src/components/Header.tsx
  src/utils/broadcastSync.ts
Labels: type:bug, priority:medium

#1251 Display only directly assigned roles in user modal
  src/components/shared/wizard/SelectContainer.tsx
  src/components/users/partials/modal/UserDetails.tsx
  src/components/users/partials/wizard/NewUserWizard.tsx
  src/components/users/partials/wizard/UserRolesTab.tsx
  src/configs/modalConfig.ts
Labels: type:usability

#1254 Changing themes of series fixed
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  src/slices/seriesDetailsSlice.ts
Labels: type:bug

#1006 Seperate user and non-user roles
  package-lock.json
  package.json
  src/components/events/partials/ModalTabsAndPages/EventDetailsAccessPolicyTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsAccessTab.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesSummary.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/users/partials/modal/AclDetails.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/components/users/partials/wizard/NewAclSummaryPage.tsx
  src/configs/modalConfig.ts
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/selectors/eventDetailsSelectors.ts
  src/selectors/seriesDetailsSelectors.ts
  src/slices/aclDetailsSlice.ts
  src/slices/aclSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/userSlice.ts
  src/utils/aclUtils.ts
  src/utils/dropDownUtils.ts
Labels: type:enhancement

#1240 Sorting capture devices by last-updated-timestamp isn't possible
  src/configs/tableConfigs/recordingsTableConfig.ts
Labels: type:bug

#1196 Uncheck 'Select all' header cell on page change
  src/components/shared/Table.tsx
Labels: type:bug, priority:low

#1306 Revert PR 1006 Separate User and Non-User Roles for 17.x
  package-lock.json
  package.json
  src/components/events/partials/ModalTabsAndPages/EventDetailsAccessPolicyTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsAccessTab.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesSummary.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/users/partials/modal/AclDetails.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/components/users/partials/wizard/NewAclSummaryPage.tsx
  src/configs/modalConfig.ts
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/selectors/eventDetailsSelectors.ts
  src/selectors/seriesDetailsSelectors.ts
  src/slices/aclDetailsSlice.ts
  src/slices/aclSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/userSlice.ts
  src/utils/aclUtils.ts
  src/utils/dropDownUtils.ts
Labels: type:enhancement

#1307 Re-Introduce PR 1006 Separate User and Non-User Roles to main/develop
  package-lock.json
  package.json
  src/components/events/partials/ModalTabsAndPages/EventDetailsAccessPolicyTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsAccessTab.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesSummary.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/users/partials/modal/AclDetails.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/components/users/partials/wizard/NewAclSummaryPage.tsx
  src/configs/modalConfig.ts
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/selectors/eventDetailsSelectors.ts
  src/selectors/seriesDetailsSelectors.ts
  src/slices/aclDetailsSlice.ts
  src/slices/aclSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/userSlice.ts
  src/utils/aclUtils.ts
  src/utils/dropDownUtils.ts
Labels: type:enhancement

#1305 Create release branch structure
  .github/demo-page.html
  .github/get-release-server.sh
  .github/workflows/create-release.yml
  .github/workflows/deploy-main.yml
  .github/workflows/deploy-test.yml
  .github/workflows/process-release.yml
Labels: type:infrastructure
