Repository opencast/opencast-admin-interface, pull requests merged in 2025-07, with the labels that each got.

#1341 Group async calls
  src/components/configuration/partials/ThemesActionsCell.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/EventsSeriesCell.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
Labels: type:code-enhancement

#1343 Make DropDown more performant for many options
  package-lock.json
  package.json
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/selectors/tableFilterSelectors.ts
Labels: type:enhancement

#1318 Added indicator for main menu
  src/App.tsx
  src/components/shared/MainNav.tsx
  src/components/systems/partials/SystemsNavigation.tsx
  src/styles/components/_menu.scss
  src/styles/mixins/_triangle-point.scss
Labels: type:visual-clarity

#1345 Activate eslint camelcase
  eslint.config.js
  package-lock.json
  package.json
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsTabHierarchyNavigation.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrorDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperationDetails.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/wizards/RenderWorkflowConfig.tsx
  src/components/shared/RegistrationModal.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/components/users/partials/wizard/NewUserGeneralTab.tsx
  src/configs/adopterRegistrationConfig.ts
  src/slices/eventDetailsSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/workflowSlice.ts
  src/utils/eventDetailsUtils.ts
  src/utils/workflowPanelUtils.ts
Labels: type:code-enhancement

#1350 Activate eslint no-non-null-asserted-optional-chain
  eslint.config.js
  src/components/shared/Tooltip.tsx
Labels: type:code-enhancement

#1353 Activate eslint unbound-method
  eslint.config.js
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
Labels: type:code-enhancement

#1371 Fix merge conflicts
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowErrorDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperations.tsx
  src/selectors/eventDetailsSelectors.ts
Labels: type:bug, type:code-enhancement

#1352 Activate eslint no-unsafe-anything
  eslint.config.js
  src/components/About.tsx
  src/components/configuration/partials/wizard/NewThemeWizard.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAssetUploadPage.tsx
  src/components/events/partials/modals/DeleteEventsModal.tsx
  src/components/events/partials/modals/DeleteSeriesModal.tsx
  src/components/events/partials/modals/EditScheduledEventsModal.tsx
  src/components/events/partials/modals/StartTaskModal.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/components/events/partials/wizards/RenderWorkflowConfig.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/MainNav.tsx
  src/components/shared/TimeSeriesStatistics.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/shared/wizard/RenderField.tsx
  src/components/shared/wizard/RenderMultiField.tsx
  src/components/shared/wizard/SelectContainer.tsx
  src/components/shared/wizard/WizardStepper.tsx
  src/components/users/partials/wizard/NewAclWizard.tsx
  src/components/users/partials/wizard/NewGroupWizard.tsx
  src/configs/statisticsConfig.ts
  src/i18n/i18n.ts
  src/index.tsx
  src/slices/aclDetailsSlice.ts
  src/slices/aclSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/groupDetailsSlice.ts
  src/slices/groupSlice.ts
  src/slices/jobSlice.ts
  src/slices/recordingDetailsSlice.ts
  src/slices/recordingSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/serverSlice.ts
  src/slices/serviceSlice.ts
  src/slices/shared/tobiraErrors.ts
  src/slices/statisticsSlice.ts
  src/slices/tableFilterSlice.ts
  src/slices/themeDetailsSlice.ts
  src/slices/themeSlice.ts
  src/slices/userDetailsSlice.ts
  src/slices/userInfoSlice.ts
  src/slices/userSlice.ts
  src/slices/workflowSlice.ts
  src/thunks/assetsThunks.ts
  src/utils/aclUtils.ts
  src/utils/adopterRegistrationUtils.ts
  src/utils/broadcastSync.ts
  src/utils/dateUtils.ts
  src/utils/embeddedCodeUtils.ts
  src/utils/resourceUtils.ts
  src/utils/statisticsUtils.ts
  src/utils/utils.ts
  src/utils/validate.ts
  vite-env.d.ts
Labels: type:code-enhancement

#1349 Activate eslint await-thenable
  eslint.config.js
  src/components/events/partials/EventsTechnicalDateCell.tsx
  src/components/shared/DateTimeCell.tsx
  src/components/shared/MultiValueCell.tsx
  src/components/shared/RegistrationModal.tsx
  src/components/shared/Stats.tsx
  src/slices/tableFilterSlice.ts
  src/thunks/tableThunks.ts
Labels: type:code-enhancement

#1348 Activate eslint spaced-comment
  eslint.config.js
  src/components/configuration/partials/wizard/BumperPage.tsx
  src/components/configuration/partials/wizard/GeneralPage.tsx
  src/components/configuration/partials/wizard/TitleSlidePage.tsx
  src/components/configuration/partials/wizard/WatermarkPage.tsx
  src/components/events/Events.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsSummaryPage.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsAddAsset.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAssetUploadPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewMetadataPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/events/partials/ModalTabsAndPages/NewTobiraPage.tsx
  src/components/events/partials/modals/DeleteSeriesModal.tsx
  src/components/events/partials/wizards/NewEventSummary.tsx
  src/components/events/partials/wizards/NewSeriesSummary.tsx
  src/components/events/partials/wizards/scheduling/SchedulingConflicts.tsx
  src/components/events/partials/wizards/summaryTables/AccessSummaryTable.tsx
  src/components/events/partials/wizards/summaryTables/MetadataSummaryTable.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/EditTableViewModal.tsx
  src/components/shared/NewResourceModal.tsx
  src/components/shared/Table.tsx
  src/components/shared/TableFilterProfiles.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/TimeSeriesStatistics.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/shared/wizard/SelectContainer.tsx
  src/components/users/partials/GroupsActionsCell.tsx
  src/components/users/partials/wizard/GroupMetadataPage.tsx
  src/components/users/partials/wizard/GroupRolesPage.tsx
  src/components/users/partials/wizard/GroupUsersPage.tsx
  src/components/users/partials/wizard/NewUserWizard.tsx
  src/components/users/partials/wizard/UserRolesTab.tsx
  src/configs/hotkeysConfig.ts
  src/configs/modalConfig.ts
  src/slices/aclSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/groupDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/tableFilterSlice.ts
  src/slices/userSlice.ts
  src/slices/workflowSlice.ts
  src/thunks/assetsThunks.ts
  src/utils/aclUtils.ts
  src/utils/adopterRegistrationUtils.ts
  src/utils/componentStyles.ts
  src/utils/embeddedCodeUtils.ts
Labels: type:code-enhancement
