Repository opencast/opencast-admin-interface, pull requests merged in 2025-02, with the labels that each got.

#1084 Fix "Typing in date input ends early"
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/wizard/RenderField.tsx
Labels: type:bug

#741 Add support for various config options in listprovider/acl.default.create.properties
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/slices/aclSlice.ts
Labels: type:bug

#1088 Fix wrong notes being displayed in notes column
  src/components/events/partials/EventsNotesCell.tsx
Labels: type:bug

#1078 Fix some Tobira integration issues
  src/components/events/partials/ModalTabsAndPages/DetailsTobiraTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewTobiraPage.tsx
  src/components/events/partials/modals/EventDetails.tsx
  src/components/events/partials/modals/SeriesDetails.tsx
  src/components/shared/Notifications.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/slices/eventDetailsSlice.ts
  src/slices/notificationSlice.ts
Labels: type:bug, type:enhancement

#856 Make next/previous buttons a bit more robust
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
Labels: type:code-enhancement

#1024 Fix request to /staticfiles failing during dev
  src/components/shared/wizard/FileUpload.tsx
Labels: type:bug

#1017 Reduce duplicate code for NavBar components
  src/components/About.tsx
  src/components/NavBar.tsx
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/events/partials/EventsNavigation.tsx
  src/components/recordings/Recordings.tsx
  src/components/shared/NewResourceModal.tsx
  src/components/statistics/Statistics.tsx
  src/components/systems/Jobs.tsx
  src/components/systems/Servers.tsx
  src/components/systems/Services.tsx
  src/components/systems/partials/SystemsNavigation.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
  src/components/users/partials/UsersNavigation.tsx
Labels: type:code-enhancement

#1018 Reduce duplicate code in action cells
  src/components/configuration/partials/ThemesActionsCell.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/EventsDateCell.tsx
  src/components/events/partials/EventsLocationCell.tsx
  src/components/events/partials/EventsPresentersCell.tsx
  src/components/events/partials/EventsSeriesCell.tsx
  src/components/events/partials/EventsStatusCell.tsx
  src/components/events/partials/EventsTechnicalDateCell.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/recordings/partials/RecordingsActionCell.tsx
  src/components/shared/ActionCellDelete.tsx
  src/components/shared/ConfirmModal.tsx
  src/components/shared/IconButton.tsx
  src/components/systems/partials/ServicesActionsCell.tsx
  src/components/users/partials/AclsActionsCell.tsx
  src/components/users/partials/GroupsActionsCell.tsx
  src/components/users/partials/UsersActionsCell.tsx
Labels: type:code-enhancement

#1053 Remove btm spacer, fix scroll bars in modals
  src/components/configuration/partials/wizard/ThemeDetails.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsGeneralPage.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewProcessingPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  src/components/events/partials/ModalTabsAndPages/StartTaskGeneralPage.tsx
  src/components/events/partials/ModalTabsAndPages/StartTaskWorkflowPage.tsx
  src/components/events/partials/modals/DeleteEventsModal.tsx
  src/components/events/partials/modals/EditMetadataEventsModal.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/styles/components/_components-config.scss
  src/styles/components/_helper-classes.scss
  src/styles/main.scss
Labels: type:bug

#1085 Fix `@mui/styled`
  package-lock.json
  package.json
  src/components/shared/Table.tsx
Labels: type:dependencies

#1008 Sort series table by date per default
  src/thunks/tableThunks.ts
Labels: type:visual-clarity

#1025 Theme upload validation workaround
  src/components/shared/wizard/FileUpload.tsx
Labels: type:bug

#1123 Update @hello-pangea/dnd to major version 18
  package-lock.json
  package.json
Labels: type:dependencies

#1107 Remove bourbon
  package-lock.json
  package.json
  src/styles/base/_variables.scss
  src/styles/components/_dropdowns.scss
  src/styles/components/_footer.scss
  src/styles/components/_form.scss
  src/styles/components/_header.scss
  src/styles/components/_menu.scss
  src/styles/components/_multi-select.scss
  src/styles/components/_simple-box.scss
  src/styles/components/_tables.scss
  src/styles/components/data-filter/_base.scss
  src/styles/components/data-filter/_filter-profiles.scss
  src/styles/components/modals/_footer.scss
  src/styles/components/modals/_header.scss
  src/styles/components/modals/_modal-alerts.scss
  src/styles/components/modals/_modal-components.scss
  src/styles/extensions/components/_tables.scss
  src/styles/main.scss
  src/styles/mixins/_mixins-bourbon.scss
  src/styles/mixins/_mixins-config.scss
  src/styles/views/_core.scss
  src/styles/views/_statistics.scss
  src/styles/views/modals/_event-series.scss
Labels: type:dependencies, type:code-enhancement

#1126 Update vite to major version 6
  package-lock.json
  package.json
  vite.config.ts
Labels: type:dependencies

#1128 Update React to major version 19
  package-lock.json
  package.json
  src/components/events/partials/modals/SeriesDetailsModal.tsx
  src/components/recordings/partials/modal/RecordingDetailsModal.tsx
  src/components/shared/ConfirmModal.tsx
  src/components/shared/EditTableViewModal.tsx
  src/components/shared/HotKeyCheatSheet.tsx
  src/components/shared/NewResourceModal.tsx
  src/components/shared/RegistrationModal.tsx
  src/components/shared/Table.tsx
  src/components/users/partials/modal/GroupDetailsModal.tsx
  src/hooks/wizardHooks.ts
Labels: type:dependencies

#914 Fix new filters not being loaded
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/recordings/Recordings.tsx
  src/components/systems/Jobs.tsx
  src/components/systems/Servers.tsx
  src/components/systems/Services.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
Labels: type:bug

#1049 Remove unused warning during bulk delete
  src/components/events/partials/modals/DeleteEventsModal.tsx
Labels: type:bug

#1050 Remove dead "todo" comments
  src/components/configuration/partials/wizard/TitleSlidePage.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/index.tsx
  src/slices/aclDetailsSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/utils/resourceUtils.ts
Labels: type:code-enhancement

#1055 Make header icons look the same when focused
  src/components/Header.tsx
  src/styles/components/_header.scss
Labels: type:visual-clarity

#1080 Assorted typing improvements
  src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/shared/Table.tsx
  src/components/users/partials/UsersActionsCell.tsx
  src/components/users/partials/UsersRolesCell.tsx
  src/configs/modalConfig.ts
  src/configs/sourceConfig.ts
  src/slices/aclDetailsSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/groupDetailsSlice.ts
  src/slices/groupSlice.ts
  src/slices/recordingDetailsSlice.ts
  src/slices/recordingSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/serverSlice.ts
  src/slices/serviceSlice.ts
  src/slices/tableFilterSlice.ts
  src/slices/tableSlice.ts
  src/slices/themeDetailsSlice.ts
  src/slices/themeSlice.ts
  src/slices/userDetailsSlice.ts
  src/slices/userSlice.ts
  src/slices/workflowSlice.ts
  src/utils/resourceUtils.ts
  src/utils/utils.ts
Labels: type:typing

#1056 Remove unused file
  src/actions/assetActions.ts
Labels: type:code-enhancement

#1072 Remove unspecified filter on clear
  src/components/shared/TableFilters.tsx
Labels: type:bug

#1105 Fix error when changing date in bulk edit metadata
  src/components/shared/wizard/RenderField.tsx
Labels: type:bug
