Repository opencast/opencast-admin-interface, pull requests merged in 2025-01, with the labels that each got.

#1010 Update @reduxjs/toolkit to 2.5.0
  package-lock.json
  package.json
  src/components/events/partials/ModalTabsAndPages/DetailsExtendedMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/recordings/Recordings.tsx
  src/components/shared/TableFilterProfiles.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
Labels: type:dependencies

#985 Use UTC consistently
  src/slices/eventSlice.ts
Labels: type:bug

#1058 `npx update-browserslist-db@latest`
  package-lock.json
Labels: type:dependencies

#1043 Update react-router to 7.1.1
  package-lock.json
  package.json
  src/App.tsx
  src/components/About.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/events/partials/SeriesTitleCell.tsx
  src/components/recordings/Recordings.tsx
  src/components/recordings/partials/RecordingsNameCell.tsx
  src/components/shared/MainNav.tsx
  src/components/statistics/Statistics.tsx
  src/components/systems/Jobs.tsx
  src/components/systems/Servers.tsx
  src/components/systems/Services.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
Labels: type:dependencies

#1048 Properly hide Tobira tab
  src/components/events/partials/modals/EventDetails.tsx
  src/components/events/partials/modals/SeriesDetails.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/selectors/seriesDetailsSelectors.ts
  src/slices/shared/tobiraErrors.ts
Labels: type:bug

#909 Unify Details Modals
  src/components/configuration/partials/ThemesActionsCell.tsx
  src/components/configuration/partials/wizard/ThemeDetails.tsx
  src/components/configuration/partials/wizard/ThemeDetailsModal.tsx
  src/components/events/partials/modals/EventDetailsModal.tsx
  src/components/events/partials/modals/SeriesDetailsModal.tsx
  src/components/recordings/partials/RecordingsActionCell.tsx
  src/components/recordings/partials/modal/RecordingDetailsModal.tsx
  src/components/shared/modals/DetailsModal.tsx
  src/components/users/partials/AclsActionsCell.tsx
  src/components/users/partials/GroupsActionsCell.tsx
  src/components/users/partials/UsersActionsCell.tsx
  src/components/users/partials/modal/AclDetailsModal.tsx
  src/components/users/partials/modal/GroupDetailsModal.tsx
  src/components/users/partials/modal/UserDetailsModal.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/styles/views/modals/_event-series.scss
Labels: type:code-enhancement

#1019 Fix date not rendering in scheduling tab
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
Labels: type:bug

#1020 Fix workflow selection for scheduled events
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
  src/slices/eventDetailsSlice.ts
Labels: type:bug

#911 Unify Scheduling pages
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/events/partials/wizards/scheduling/SchedulingConflicts.tsx
  src/components/events/partials/wizards/scheduling/SchedulingEndDateDisplay.tsx
  src/components/events/partials/wizards/scheduling/SchedulingInputs.tsx
  src/components/events/partials/wizards/scheduling/SchedulingLocation.tsx
  src/components/events/partials/wizards/scheduling/SchedulingTime.tsx
Labels: type:code-enhancement

#1082 Remove deprecated `@types/dompurify`
  package-lock.json
  package.json
Labels: type:dependencies

#907 Remove WizardStepperEvent.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/shared/wizard/WizardStepper.tsx
  src/components/shared/wizard/WizardStepperEvent.tsx
  src/utils/validate.ts
Labels: type:code-enhancement

#1054 WizardNavigationButtons everywhere - Part 2
  src/components/configuration/partials/wizard/ThemeDetails.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsExtendedMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsGeneralPage.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewProcessingPage.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  src/components/events/partials/ModalTabsAndPages/NewTobiraPage.tsx
  src/components/events/partials/ModalTabsAndPages/SeriesDetailsThemeTab.tsx
  src/components/events/partials/ModalTabsAndPages/StartTaskGeneralPage.tsx
  src/components/events/partials/ModalTabsAndPages/StartTaskWorkflowPage.tsx
  src/components/events/partials/modals/DeleteEventsModal.tsx
  src/components/events/partials/modals/DeleteSeriesModal.tsx
  src/components/events/partials/modals/EditMetadataEventsModal.tsx
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/shared/NavigationButtons.tsx
  src/components/shared/wizard/WizardNavigationButtons.tsx
  src/components/users/partials/modal/AclDetails.tsx
  src/components/users/partials/modal/GroupDetails.tsx
  src/components/users/partials/modal/UserDetails.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/components/users/partials/wizard/NewUserWizard.tsx
Labels: type:code-enhancement

#1061 Remove useless calls to `then`
  src/components/events/partials/modals/EventDetails.tsx
Labels: type:code-enhancement

#1060 Fix whitespace issues
  src/components/events/Events.tsx
  src/components/events/Series.tsx
Labels: type:code-enhancement

#1087 Fix notes cannot be edited in notes column
  src/slices/eventDetailsSlice.ts
Labels: type:bug

#1047 Group minor dependabot updates
  .github/dependabot.yml
Labels: type:dependencies, type:infrastructure

#1046 Reduce duplicate code for modals
  src/components/Header.tsx
  src/components/configuration/Themes.tsx
  src/components/configuration/partials/ThemesActionsCell.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/ModalTabsAndPages/DetailsTobiraTab.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/events/partials/modals/DeleteEventsModal.tsx
  src/components/events/partials/modals/DeleteSeriesModal.tsx
  src/components/events/partials/modals/EditMetadataEventsModal.tsx
  src/components/events/partials/modals/EditScheduledEventsModal.tsx
  src/components/events/partials/modals/EmbeddingCodeModal.tsx
  src/components/events/partials/modals/EventDetailsModal.tsx
  src/components/events/partials/modals/SeriesDetailsModal.tsx
  src/components/events/partials/modals/StartTaskModal.tsx
  src/components/recordings/partials/RecordingsActionCell.tsx
  src/components/recordings/partials/modal/RecordingDetailsModal.tsx
  src/components/shared/ConfirmModal.tsx
  src/components/shared/EditTableViewModal.tsx
  src/components/shared/HotKeyCheatSheet.tsx
  src/components/shared/NewResourceModal.tsx
  src/components/shared/RegistrationModal.tsx
  src/components/shared/Table.tsx
  src/components/shared/modals/Modal.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
  src/components/users/partials/AclsActionsCell.tsx
  src/components/users/partials/GroupsActionsCell.tsx
  src/components/users/partials/UsersActionsCell.tsx
  src/components/users/partials/modal/GroupDetailsModal.tsx
Labels: type:code-enhancement

#1021 Fix notification display in event metadata tab
  src/components/configuration/Themes.tsx
  src/components/configuration/partials/wizard/GeneralPage.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsCommentsTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsPublicationTab.tsx
  src/components/events/partials/modals/EventDetails.tsx
  src/components/recordings/Recordings.tsx
  src/components/shared/Notifications.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/systems/Jobs.tsx
  src/components/systems/Servers.tsx
  src/components/systems/Services.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
  src/components/users/partials/wizard/NewAclSummaryPage.tsx
  src/components/users/partials/wizard/NewGroupSummaryPage.tsx
  src/components/users/partials/wizard/NewUserGeneralTab.tsx
  src/slices/eventDetailsSlice.ts
Labels: type:bug

#1051 Clear modal notifs when opening modal
  src/components/events/partials/wizards/NewEventWizard.tsx
  src/components/events/partials/wizards/NewSeriesWizard.tsx
  src/slices/notificationSlice.ts
  src/slices/seriesDetailsSlice.ts
Labels: type:bug

#738 Respect publication channels listprovider more
  src/components/events/partials/ModalTabsAndPages/EventDetailsPublicationTab.tsx
  src/components/events/partials/PublishedCell.tsx
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/thunks/assetsThunks.ts
Labels: type:bug
