Repository opencast/opencast-admin-interface, pull requests merged in 2025-08, with the labels that each got.

#1372 Activate eslint require-await
  eslint.config.js
  src/components/events/partials/EventsStatusCell.tsx
  src/components/events/partials/ModalTabsAndPages/EditScheduledEventsEditPage.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowDetails.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowOperations.tsx
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
  src/components/events/partials/modals/EditScheduledEventsModal.tsx
  src/components/shared/RegistrationModal.tsx
  src/components/shared/Stats.tsx
  src/components/shared/Table.tsx
  src/components/shared/TableFilters.tsx
  src/components/shared/TimeSeriesStatistics.tsx
  src/components/shared/wizard/SelectContainer.tsx
  src/components/shared/wizard/WizardStepper.tsx
  src/components/systems/partials/ServersMaintenanceCell.tsx
  src/components/systems/partials/ServicesActionsCell.tsx
  src/components/users/partials/modal/AclDetails.tsx
  src/components/users/partials/wizard/AclAccessPage.tsx
  src/components/users/partials/wizard/UserEffectiveRolesTab.tsx
  src/slices/aclDetailsSlice.ts
  src/slices/aclSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/groupDetailsSlice.ts
  src/slices/groupSlice.ts
  src/slices/notificationSlice.ts
  src/slices/recordingSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/slices/seriesSlice.ts
  src/slices/serverSlice.ts
  src/slices/serviceSlice.ts
  src/slices/themeDetailsSlice.ts
  src/slices/themeSlice.ts
  src/slices/userDetailsSlice.ts
  src/slices/userSlice.ts
  src/store.ts
  src/thunks/tableThunks.ts
  src/thunks/taskThunks.ts
  src/utils/aclUtils.ts
  src/utils/bulkActionUtils.ts
  src/utils/dateUtils.ts
Labels: type:code-enhancement

#1389 Fix schedule datepicker not working
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
Labels: type:bug

#1384 Fix datepicker opening twice on start date
  src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
Labels: type:bug

#1390 Show unsaved changes warning on tab switch
  src/components/events/partials/modals/EventDetails.tsx
  src/components/events/partials/modals/EventDetailsModal.tsx
  src/components/events/partials/modals/SeriesDetails.tsx
  src/components/events/partials/modals/SeriesDetailsModal.tsx
  src/utils/utils.ts
Labels: type:bug

#1369 Reduce duplicate code in main page
  src/components/About.tsx
  src/components/NavBar.tsx
  src/components/configuration/Themes.tsx
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/recordings/Recordings.tsx
  src/components/shared/MainPage.tsx
  src/components/shared/Table.tsx
  src/components/shared/TablePage.tsx
  src/components/statistics/Statistics.tsx
  src/components/systems/Jobs.tsx
  src/components/systems/Servers.tsx
  src/components/systems/Services.tsx
  src/components/users/Acls.tsx
  src/components/users/Groups.tsx
  src/components/users/Users.tsx
Labels: type:code-enhancement

#1382 Clicking on roles in user table to set filter
  src/components/users/partials/UsersRolesCell.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:enhancement

#1416 Fix appliance of series ACL to new event
  src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx
Labels: type:bug
