Repository opencast/opencast-admin-interface, pull requests merged in 2025-06, with the labels that each got.

#1323 Remove redundant `parameter: undefined` from calls to `addNotification`
  src/components/events/partials/ModalTabsAndPages/DetailsTobiraTab.tsx
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/components/events/partials/ModalTabsAndPages/NewTobiraPage.tsx
  src/components/events/partials/modals/EventDetails.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/shared/wizard/FileUpload.tsx
  src/slices/aclSlice.ts
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
  src/slices/seriesDetailsSlice.ts
  src/utils/bulkActionUtils.ts
Labels: type:code-enhancement

#1325 Use proper keys in `DetailsMetadataTab`
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
Labels: type:code-enhancement

#1321 Correctly install optional native dependencies
  package-lock.json
Labels: type:dependencies, type:infrastructure

#1327 Remove unnecessary state
  src/components/events/partials/modals/EditMetadataEventsModal.tsx
Labels: type:code-enhancement

#1298 Add "Metadata saved" notification
  src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/slices/eventDetailsSlice.ts
Labels: type:visual-clarity

#1322 Direct link to the Tobira video/series
  src/components/events/partials/ModalTabsAndPages/DetailsTobiraTab.tsx
  src/slices/eventDetailsSlice.ts
  src/slices/seriesDetailsSlice.ts
Labels: type:enhancement, type:usability

#1329 Fix service and servers filters being applied to the wrong tables
  src/components/events/partials/EventsLocationCell.tsx
  src/components/events/partials/EventsSeriesCell.tsx
  src/components/events/partials/EventsTechnicalDateCell.tsx
  src/components/shared/DateTimeCell.tsx
  src/components/shared/MultiValueCell.tsx
  src/components/shared/Stats.tsx
  src/components/shared/TableFilters.tsx
  src/slices/tableFilterSlice.ts
Labels: type:bug

#1332 Make drag and drop instructions translatable
  src/components/shared/EditTableViewModal.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:bug, type:accessibility

#1334 Accessibility concerns in events stats
  src/components/shared/Stats.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/styles/components/_stats.scss
Labels: type:accessibility

#1336 Add autofocus for saved filter sets
  src/components/shared/TableFilterProfiles.tsx
Labels: type:accessibility

#1338 Dock saved filter sets modal to the right
  src/styles/components/data-filter/_filter-profiles.scss
Labels: type:visual-clarity

#1299 Persist table sort
  src/store.ts
Labels: type:usability

#1311 Increase subtab contrast
  src/components/events/partials/ModalTabsAndPages/EventDetailsAssetsTab.tsx
  src/styles/base/_variables.scss
Labels: type:accessibility
