Repository opencast/opencast-admin-interface, pull requests merged in 2025-09, with the labels that each got.

#1408 Use formik 'FastField' instead of 'Field' for performance reasons
  src/components/shared/Field.tsx
Labels: type:bug, type:usability

#1383 Fix Metadata field getting cut off
  src/styles/components/modals/_modal-base.scss
  src/styles/main.scss
Labels: type:visual-clarity

#1391 More explanations for embedd modal
  src/components/events/partials/modals/EmbeddingCodeModal.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
Labels: type:usability

#1375 Make event metadata load faster by fetching series options asynchronously
  src/components/shared/DropDown.tsx
  src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
  src/components/shared/wizard/RenderField.tsx
  src/utils/resourceUtils.ts
Labels: type:enhancement

#1376 fix/1283-input-unselect
  src/components/events/partials/ModalTabsAndPages/EventDetailsSchedulingTab.tsx
  src/slices/eventDetailsSlice.ts
  src/slices/eventSlice.ts
Labels: type:bug

#825 Optional terms of use dialog for user
  src/components/Header.tsx
  src/components/shared/TermsOfUseModal.tsx
  src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
  src/styles/extensions/views/modals/_registration.scss
Labels: type:enhancement, priority:medium

#1387 Fix/modal keyboard nav 950
  src/components/events/partials/ModalTabsAndPages/NewMetadataPage.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/NewResourceModal.tsx
  src/components/shared/modals/Modal.tsx
  src/components/shared/wizard/RenderMultiField.tsx
  src/hooks/wizardHooks.ts
Labels: type:usability

#1433 Disable tooltips on tables due to performance issues
  src/components/configuration/partials/ThemesActionsCell.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/EventsDateCell.tsx
  src/components/events/partials/EventsLocationCell.tsx
  src/components/events/partials/EventsPresentersCell.tsx
  src/components/events/partials/EventsSeriesCell.tsx
  src/components/events/partials/EventsStatusCell.tsx
  src/components/events/partials/EventsTechnicalDateCell.tsx
  src/components/events/partials/PublishedCell.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/events/partials/SeriesContributorsCell.tsx
  src/components/events/partials/SeriesDateTimeCell.tsx
  src/components/events/partials/SeriesOrganizersCell.tsx
  src/components/events/partials/SeriesTitleCell.tsx
  src/components/recordings/partials/RecordingsActionCell.tsx
  src/components/recordings/partials/RecordingsNameCell.tsx
  src/components/shared/ActionCellDelete.tsx
  src/components/shared/DateTimeCell.tsx
  src/components/shared/MultiValueCell.tsx
  src/components/systems/partials/ServicesActionsCell.tsx
  src/components/users/partials/AclsActionsCell.tsx
  src/components/users/partials/GroupsActionsCell.tsx
  src/components/users/partials/UsersActionsCell.tsx
Labels: type:bug

#1435 Don't render series modal in action cells
  src/components/events/Events.tsx
  src/components/events/Series.tsx
  src/components/events/partials/EventActionCell.tsx
  src/components/events/partials/SeriesActionsCell.tsx
  src/components/events/partials/modals/EventDetailsModal.tsx
  src/components/events/partials/modals/SeriesDetails.tsx
  src/components/events/partials/modals/SeriesDetailsModal.tsx
  src/selectors/seriesDetailsSelectors.ts
  src/slices/seriesDetailsSlice.ts
Labels: type:bug

#1444 Take advantage of all available space for dropdowns in metadata modals
  src/components/shared/wizard/RenderField.tsx
Labels: type:visual-clarity, type:accessibility, type:usability

#1443 Improvement: Update the submitter display in the event details tab
  src/components/events/partials/ModalTabsAndPages/EventDetailsWorkflowTab.tsx
Labels: type:enhancement
